### ISSUE TITLE
Question: Parent's Enabled state change

### ISSUE THREAD

**Issue by artelogic-com** [graphics32/graphics32#190] opened 2022-06-02 10:45 UTC
How is a TCustomImage32 or TCustomPaintBox32 informed, when the parent changes its Enabled state?

**Comment by andersmelander** [comment] 2022-06-02 11:31
You mean the parent controls Enabled state?
I haven't looked but I would guess that it's handled at the `TControl`/`TWinControl` level (via a `CM_ENABLEDCHANGED` message) like it is for every other control.

**Comment by artelogic-com** [comment] 2022-06-02 11:55
I expected it to be like this, but it seems to be not the case. At least with FPC.
Tested with Win32 and GTK.

Or am I doing something wrong?
TMyControl = class(TCustomImage32)
...
protected
    procedure CMEnabledChanged(var Message: TLMessage); message CM_ENABLEDCHANGED;
...
end;

MyControl is put on a TPanel. Then I switch Enabled of Panel to False. CMEnabledChanged of my MyControl is never called. TEdit-Control on the same Panel get grayed out.

If I set Enabled of MyControl directly, CMEnabledChanged is called and everything works as expected.

**Comment by andersmelander** [comment] 2022-06-02 12:41
I just looked at the VCL source and it seems that `CM_ENABLEDCHANGED` is not broadcast to child controls so this behavior appears to be by design.

I don't know what it is you're attempting to do but child controls are probably invalidated when the parent is disabled so you might be able to detect it on repaint.

**Comment by andersmelander** [comment] 2022-06-02 13:52
> And since I have a layered controlled, that would mean to draw all layers to the buffer in every Paint-event, which is not neccesary in 99.99% of Paint-events but only in that one triggered by an Enabled-change.

TImage32 takes care of that internally; It only repaint the layers when their content has changed.

**Comment by andersmelander** [comment] 2022-06-05 21:48
Please close this issue if the question has been answered.

**Closed** 2022-06-06 07:14 UTC
Labels: question
