### ISSUE TITLE
PolyPolygonTS equivalent

### ISSUE THREAD

**Issue by PlanetIrata** [graphics32/graphics32#262] opened 2023-08-17 14:07 UTC
Hi,

I'm upgrading an old Delphi app to the latest version of Graphics32 and can't find how to upgrade this line of code since `PolyPolygonTS` don't existe anymore:

`PolyPolygonTS(Buffer, Polygon, SetAlpha(FOuterColor, 192), pfWinding);`

Thanks for your help!

**Comment by PlanetIrata** [comment] 2023-08-17 14:16
Ok, solved by using `PolyPolygonFS` and changing my `TArrayOfArrayOfFixedPoint` with a `TArrayOfArrayOfFloatPoint`

**Comment by andersmelander** [comment] 2023-08-17 14:37
You closed this while I was typing, but I'll leave this here now that I've taken the time to type it :-)

As far as I remember, the TS in `PolyPolygonTS` means **T**ransparent & **S**afe (i.e. clipped), and I also believe you're operating with integer coordinates.

First of all, the new polygon rasterizer uses either float or fixed point precision, so you will need to convert your polygon from integer coordinates to float coordinates. Something like this:

```delphi
function BuildPolygon(const Data: array of TPoint): TArrayOfFloatPoint;
var
  Index: Integer;
begin
  SetLength(Result, Length(Data));
  if Length(Data) = 0 then 
    Exit;
  for Index := 0 to High(Data) do
  begin
    Result[Index].X := Data[Index].X;
    Result[Index].Y := Data[Index].Y;
  end;
end;
```

All the new polygon functions clip coordinates so they are "safe" and they also all use transparency.

Then you can either use the "new" `TCanvas32` class in `GR32_Paths`to draw your polygon:

```delphi
function DrawPolygon(Buffer: TBitmap32; const Polygon: TArrayOfFloatPoint; Color: TColor32);
var
  Canvas: TCanvas32;
  Stroke: TStrokeBrush;
begin
  Canvas := TCanvas32.Create(Buffer);
  try
    // I'm doing a stroke here. You'll probably want a fill instead. TSolidBrush does that.
    Stroke := TStrokeBrush(Canvas.Brushes.Add(TStrokeBrush));
    Stroke.StrokeWidth := 1.5;
    Stroke.FillColor := Color;
    Canvas.Polygon(Polygon);
  finally
    Canvas.Free;
  end;
end;
```
...or you can simply use the `Polygon*` functions in `GR32_Polygons`:
```delphi
PolygonFS(Buffer, Polygon, Color, pfWinding);
```

**Comment by PlanetIrata** [comment] 2023-10-18 14:50
I repoen this Issue since I can't achieve to get the GR32 1.7 behavior. Here is my full function that is called in the PaintStage to crop selection box with a light gray (192 alpha white) outer color:

```pascal
procedure TTwDialogEditImage.imvCropPaintStage(Sender: TObject; Buffer: TBitmap32; StageNum: Cardinal);
var
  Polygon: TArrayOfArrayOfFloatPoint;
  r: TFloatRect;
begin
  if lblNoCropping.Visible then
    Exit;

  r := FCropLayer.GetAdjustedLocation();

  SetLength(Polygon, 2);
  SetLength(Polygon[0], 5);
  SetLength(Polygon[1], 5);

  // The outer rectangle. It must be given with counter clock winding.
  Polygon[0][0] := FloatPoint(0, 0);
  Polygon[0][1] := FloatPoint(imvCrop.Buffer.Width, 0);
  Polygon[0][2] := FloatPoint(imvCrop.Buffer.Width, imvCrop.Buffer.Height);
  Polygon[0][3] := FloatPoint(0, imvCrop.Buffer.Height);
  Polygon[0][4] := FloatPoint(0, 0);

  // The inner rectangle is drawn with reverse winding.
  Polygon[1][0] := FloatPoint(r.Left, r.Top);
  Polygon[1][1] := FloatPoint(r.Left, r.Bottom);
  Polygon[1][2] := FloatPoint(r.Right, r.Bottom);
  Polygon[1][3] := FloatPoint(r.Right, r.Top);
  Polygon[1][4] := FloatPoint(r.Left, r.Top);

  PolyPolygonFS(Buffer, Polygon, SetAlpha(FOuterColor, 192), pfWinding);
end;
```

(Note that I was using PolyXXX functions)

When I move the crop rectangle here is what happen:

<img width="647" alt="image" src="https://github.com/graphics32/graphics32/assets/1729529/37effbc3-26eb-464b-966c-6b2ac5eacd58">

With GR32 1.7 here was the result when moving the cropping rectangle:

<img width="967" alt="image" src="https://github.com/graphics32/graphics32/assets/1729529/b5166826-32a3-426b-9d18-d749708caffb">

Thanks for your help!

**Comment by andersmelander** [comment] 2023-10-19 02:14
`PolyPolygonFS` works so the problem is elsewhere.

There have been significant changes in the repaint logic of `TImgView32` since version 1.7 so that is more likely the cause of your problem.

That said, I just tried to reproduce with a `TImgView32` and a `TRubberbandLayer` and it worked fine...
![billede](https://github.com/graphics32/graphics32/assets/18141921/fd44fee2-27fb-4756-9970-b6b01891388e)

If you can attach a minimal example that reproduces the problem I will look into it.

**Comment by andersmelander** [comment] 2023-10-19 02:24
> There have been significant changes in the repaint logic of TImgView32 since version 1.7 so that is more likely the cause of your problem.

Yes, I think this must be it.
The current version of `TImgView32` optimizes repaints to only paint the stuff that has changed. However, since you are not using a layer to paint and you are painting outside the layer being moved (the rubberband layer), the repaint mechanism doesn't know that it needs to redraw the whole image. The fact that it worked in the old version was actually a bug in the repaint mechanism - It repainted far too much and too often.

I think if you do an `Image.Invalidate` in the `OnChange` event handler of the rubberband layer then it will work.

**Closed** 2023-10-23 14:59 UTC
Labels: question
