### ISSUE TITLE
TCanvas32.DrawPath doesn't handle overlaps

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#185] opened 2022-05-14 16:48 UTC
DrawPath draws complex figures containing mixed closed and not closed paths in separate passes, so these vectors are treated as separate figures and their overlaps are visible .

The first figure is  when the three paths are not closed the second one is given when the path of circle is closed  .

![brush](https://user-images.githubusercontent.com/40634105/168441100-07212611-0f04-4654-bbab-36759d2ceb44.png)

```
var
  img:TImage32;
  C:TCanvas32;
  Stroke:TStrokeBrush;
begin
   img:=TImage32.Create(Self);
   img.AutoSize:=True;
   img.Parent:=Self;
   Img.Bitmap.SetSize(600,400);
   Img.Bitmap.Clear(clWhite32);
   C:=TCanvas32.Create(Img.Bitmap);
   Stroke:= C.Brushes.Add(TStrokeBrush) as TStrokeBrush;
   Stroke.StrokeWidth:=20;
   Stroke.FillColor:=SetAlpha(clRed32,50);
   C.BeginUpdate;
   with C do
   begin
     MoveTo(101,45);//line
     LineTo(226,171);
     EndPath(False);
    MoveTo(163,192);//Circle
     CurveTo(117,191, 79,154, 80,108);
     CurveTo(80,62, 117,24, 163,25);
     CurveTo(210,25, 247,62, 247,108);
     CurveTo(246,155, 209,192, 163,192);
     EndPath(True);
    MoveTo(142,164);// letter P.
     CurveTo(142,164, 142,63, 142,63);
     CurveTo(142,63, 174,63, 174,63);
     CurveTo(188,63, 202,76, 201,91);
     CurveTo(201,106, 188,119, 173,119);
     CurveTo(173,119, 146,119, 146,119);
     EndPath(False);
   end;
   C.EndUpdate;
```

**Comment by andersmelander** [comment] 2022-05-31 21:20
I've thought long and hard about this problem and it seems to me that it's caused by a combination of a design flaw in `TCanvas32` and some missing functionality in `TStrokeBrush.PolyPolygonFS`/`BuildPolyPolyLine`. As far as I can see, the way those are currently implemented, there's no simple way to solve the problem

One possible solution could be to move the handling of mixed open/closed polylines/polygons from `TCanvas32` to `TStrokeBrush.PolyPolygonFS` or `BuildPolyPolyLine`. This way all the resulting polylines/polygons could be rendered in one go instead of in multiple passes as they are now. I'll see if I can make that work.

**Comment by andersmelander** [comment] 2022-05-31 23:14
I've committed a solution to the **bugfix/TCanvas32_DrawPath** branch. I used your example as a test case.
I'm thinking this might also have been relevant for #107.

Anyway, give it a try.

**Comment by lamdalili** [comment] 2022-06-06 19:25
Thanks for help and code

>One possible solution could be to move the handling of mixed open/closed polylines/polygons from TCanvas32 to TStrokeBrush.PolyPolygonFS or BuildPolyPolyLine.

Still useless without changing the bad data structure shared between `TCanvas32 `and `TBrush`  (`TArrayOfArrayOfFloatPoint`) intended only for fill operations. a good solution is to move the pen operations to a separate class having brush as a member property.

here another situation when you try to implement arc line join, you need to know segments curvature which is not available at this level.

![arc-line-join](https://user-images.githubusercontent.com/40634105/172224683-3cf02e9c-2eaa-4d0c-a08b-a4280b6ad0c1.png)

I simplified the solution by removing `PathClosed `from `TFlattenedPath`, which was bad design because there are many other geometric  entities  need to be treated as a whole with new  data structure  . So  the trick adopted  is  when the path is closed, the first and the last point must have the same value otherwise make sure they have different values.. this is not the best solution but allows to StrokBrush to work properly without   adding more complexity to this limited implementation.

portion modified in `TFlattenedPath.EndPath`
```
  if (Close) then
  begin
    AddPoint(FPoints[0]);
    CurrentPoint := FPoints[0];
  end else if(FPoints[0]= FPoints[FPointIndex-1]) then
     FPoints[0].X:=FPoints[0].X+0.0001;
```
New virual method added `TStrokeBrush.BuildStrokePath`
Method deleted `TDashedBrush.PolyPolygonFS`
```
procedure TStrokeBrush.PolyPolygonFS(Renderer: TCustomPolygonRenderer;
  const Points: TArrayOfArrayOfFloatPoint; const ClipRect: TFloatRect;
  Transformation: TTransformation );
var
  I,L,J,S: Integer;
  Tmp,Polys:TArrayOfArrayOfFloatPoint;
begin
  Polys:=nil;
  S:=0;
  for I := 0 to High(Points) do
  begin
      Tmp:= BuildStrokePath(Points[I]);
      L:=Length(Tmp);
      SetLength(Polys,S+L);
      for J := 0 to L-1 do  //merge
        Polys[S+J]:=Tmp[J];
      inc(S,L);
  end;
  inherited PolyPolygonFS(Renderer, Polys, ClipRect, Transformation);
end;

function TStrokeBrush.BuildStrokePath(const Points: TArrayOfFloatPoint): TArrayOfArrayOfFloatPoint;
var
  t:TArrayOfArrayOfFloatPoint;
begin
  SetLength(t,1);
  t[0]:=Points;
  Result := BuildPolyPolyline(t, IsClosed(Points), StrokeWidth, JoinStyle,
               EndStyle, MiterLimit);
end;

function TDashedBrush.BuildStrokePath(const Points: TArrayOfFloatPoint): TArrayOfArrayOfFloatPoint;
begin
  if Length(FDashArray)<>0 then
  begin
    Result:= BuildDashedLine(Points, FDashArray, FDashOffset,IsClosed(Points));
    Result:= BuildPolyPolyline(Result,false, StrokeWidth, JoinStyle,
              EndStyle, MiterLimit);
  end else
    Result:= inherited;
end;
```
simple helper `IsClosed`
 ```
function IsClosed(const t: TArrayOfFloatPoint):boolean;
var
 Len:integer;
begin
    Len:=Length(t);
    if Len<3 then
      Exit(False);
    Result:=(t[0] = t[Len-1]);
end;
```

**Comment by andersmelander** [comment] 2022-06-06 20:20
I don't think I understand.

Can you please post two code snippets which demonstrate the problem:
1. Draw a figure using TCanvas32 (should exhibit the problem)
2. Draw a figure not using TCanvas32 (should not exhibit the problem)

**Comment by lamdalili** [comment] 2022-06-06 22:33
Same code posted in the first post with some tests with TDashedBrush as it has the same problem - this issue is fixed now.. 

The figure above was my intention to implement ArcLineJoin in the past I abandoned due to the design of TCanvas32 and TStrokeBrush.

**Comment by andersmelander** [comment] 2022-06-07 15:57
> Same code posted in the first post with some tests with TDashedBrush as it has the same problem - this issue is fixed now..

As far as I can tell _this_ issue is resolved as your problems with arc line joins are beyond the issue scope.

I'll create a new issue about arc line joins.

**Comment by lamdalili** [comment] 2022-06-07 20:45
Please delete the last commit even if it solves the problem but it shouldn't be part of the library, the code adds unnecessary complexity for marginal benefit and propagates the design error :)

**Comment by andersmelander** [comment] 2022-06-07 21:55
I disagree.
This issue demonstrated a real deficiency in an existing feature, namely the handling of mixed open/closed paths. That issue has now been resolved.

It may very well be that the solution complicates things for your effort to implement arc line joins and that the whole thing will have to be redesigned but we'll cross that bridge when and if we come to it.
So far I have only seen a very vague outline of some TCanvas32 changes and no explanation of how these would enable you to implement arc line joins. This is not enough information to base a decision on.

**Comment by lamdalili** [comment] 2023-04-27 20:13
>I'm thinking this might also have been relevant for  #107.

By default TextToPath is rendered with oddeven winding rule, so any intersection area becomes visible, mainly in case of cursive font or strikethrough text.

**Comment by andersmelander** [comment] 2023-04-27 20:27
> By default path generated by TextToPath is rendered with oddeven winding rule

Where?

FWIW, I believe the normal way to render a text poly-polygon would be to use a `TSolidBrush` with `FillMode` set to `pfNonZero` (the default). What am I missing?

**Comment by lamdalili** [comment] 2023-04-27 20:42
> I believe the normal way to render a text poly-polygon would be to use a TSolidBrush with FillMode set to pfNonZero (the default). What am I missing?


No, it's not possible with the text path at least in the same run, the curent structure used to hold path text is very poor just ArrayOfArrayOfPoint which doesn't help to distinguish it

**Comment by andersmelander** [comment] 2023-04-27 21:03
> No, it's not possible with the text path at least in the same run

Not possible? Works fine for me:

**`TStrokeBrush`**
![billede](https://user-images.githubusercontent.com/18141921/234989784-1cc1e9d4-4015-481e-b158-c08dd81ed533.png)

**`TSolidBrush`**
![billede](https://user-images.githubusercontent.com/18141921/234989822-a5085e09-ac38-43c6-b759-29af98d0769a.png)

**Comment by lamdalili** [comment] 2023-04-27 21:19
I'm not sure understand the last case I haven’t done any test later ,  
but the issue 107 is due to that fact.
I'll try understand


thanks

**Comment by lamdalili** [comment] 2024-04-05 04:30
Problem not fixed for TDashedBrush it produce the same anomaly,, there are three almost identical methods  that make it hard to guess  which one to implement :

```
procedure DoPolyPolygonFS(Renderer: TCustomPolygonRenderer;
    const Points: TArrayOfArrayOfFloatPoint;
    const ClipRect: TFloatRect; Transformation: TTransformation;
    Closed: Boolean); virtual;

procedure PolyPolygonFS(Renderer: TCustomPolygonRenderer;
    const Points: TArrayOfArrayOfFloatPoint;
    const ClipRect: TFloatRect; Transformation: TTransformation;
    Closed: Boolean); overload; virtual;

procedure PolyPolygonFS(Renderer: TCustomPolygonRenderer;
    const Points: TArrayOfArrayOfFloatPoint;
    const ClipRect: TFloatRect; Transformation: TTransformation;
    Closed: TBooleanArray); overload; virtual;
```
I suggest  creating a single method having both overloaded paramaters  `Closed` to avoid using global variables `FBuffer` & `FCurrentIndex` , so that  all  the work will be focused around this new method:

in this version if `Closeds `is present `DefaultClosed` has no effet 
```
procedure PolyPolygonFS(Renderer: TCustomPolygonRenderer;
      const Points: TArrayOfArrayOfFloatPoint;
      const ClipRect: TFloatRect; Transformation: TTransformation;
      DefaultClosed: Boolean; Closeds: TBooleanArray); overload; virtual;
```

**Comment by andersmelander** [comment] 2024-04-05 10:40
> Problem not fixed for TDashedBrush it produce the same anomaly,, there are three almost identical methods that make it hard to guess which one to implement :

Is this the "anomaly" you mean?
![billede](https://github.com/graphics32/graphics32/assets/18141921/fcceada5-7fa9-49d7-b080-eb194b9c1184)

I think that case is well beyond what TCanvas32 is meant to handle.

I suspect that what you wanted was for all the dashes to be merged into non-overlapping polygons so they could be drawn in one go without semi-transparency issues, right? If this is what you want then you should merge the polygons before passing them to TCanvas32 (you can use Clipper or something like it for that). Graphics32 itself does not contain functionality to calculate the union of a set of polygons. It does contain a copy of Clipper but Clipper's functionality isn't integrated as that would kill performance.
See the [Clipper example](https://github.com/graphics32/graphics32/tree/master/Examples/Drawing/Clipper).

> there are three almost identical methods that make it hard to guess which one to implement

Yes, the `TCustomBrush` class hierarchy isn't very well designed. My guess is that it was a work-in-progress that was never completed - just like TCanvas32 before I rewrote it. I will create a new issue to consider what can be done about it.

**Comment by lamdalili** [comment] 2024-04-05 12:18
> I suspect that what you wanted was for all the dashes to be merged into non-overlapping polygons so they could be drawn in one go without semi-transparency issues, right?

Yes it's about that , 
Currently I'm using an old code from old version that I've modified and it works for years,
now I want to update to a new version and see if everything will pass fine, so I noticed the problem and I remembered this old bug.

**Comment by andersmelander** [comment] 2024-04-05 20:33
I've had a think about how this can be solved and it has dawned on me that the problem simply is that the polypolygons are rendered too soon.

Right now we render like this (using `TStrokeBrush` as an example):


- For each brush (`TCanvas32.DrawPath`):
  - **TStrokeBrush**
    - For all polypolyline **A** in the path (`TStrokeBrush.PolyPolygonFS`):
      - Build a new polypolygon **B** from the polypolyline **A** using the stroke settings (`BuildPolyPolyLine`)
    - Render the polypolygon **B** (`TCustomBrush.PolyPolygonFS`)
  - **TDashedBrush**
    - For each polyline **A** in the path (`TDashedBrush.PolyPolygonFS`):
      - Build a new polypolyline **B** from the polyline **A** using the dashed stroke settings (`BuildDashedLine`)
      - Build a new polypolygon **C** from the dashed polypolyline **B** using the stroke settings (`BuildPolyPolyLine`)
      - Render the polypolygon **C**

The sequence for TStrokeBrush is correct but for TDashedBrush, instead of rendering each polyline after it has been made into a polypolygon, we should be collecting them all into one big polypolygon and then only render that once we have them all. Like this:

  - **TDashedBrush**
    - For each polyline **A** in the path (`TDashedBrush.PolyPolygonFS`):
      - Build a new polypolyline **B** from the polyline **A** using the dashed stroke settings (`BuildDashedLine`)
      - Build a new polypolygon **C** from the dashed polypolyline **B** using the stroke settings (`BuildPolyPolyLine`)
      - Add the polypolygon **C** to the polypolygon **D**
    - Render the polypolygon **D**

The change required to implement his should be minimal and will not require any API changes. Let me just try [...2 minutes later...]:
![billede](https://github.com/graphics32/graphics32/assets/18141921/4d881fc4-cf3b-4563-851a-7b2d174cc602)

And this is the fix:

```
procedure TDashedBrush.PolyPolygonFS(Renderer: TCustomPolygonRenderer;
  const Points: TArrayOfArrayOfFloatPoint; const ClipRect: TFloatRect;
  Transformation: TTransformation; Closed: Boolean);
var
  I: Integer;
  DashedLines: TArrayOfArrayOfFloatPoint;
begin
  DashedLines := nil;
  for I := 0 to High(Points) do
    DashedLines := DashedLines + BuildDashedLine(Points[I], FDashArray, FDashOffset, Closed);

  inherited PolyPolygonFS(Renderer, DashedLines, ClipRect, Transformation, False);
end;
```

There still is a problem with TDashedBrush and mixed open/closed polygons. It seems TDashedBrush incorrectly falls back to TStrokedBrush in this case but that problem is unrelated to the above.

**Comment by andersmelander** [comment] 2024-04-06 01:05
> There still is a problem with TDashedBrush and mixed open/closed polygons.

Fixed; I have now completely redesigned `TCustomBrush`. This is a breaking change (if you have implemented custom brushes).

**Comment by andersmelander** [comment] 2024-04-06 01:08
> if you have implemented custom brushes

I made a few in the Curves example just to _dog-food_ the design.
![billede](https://github.com/graphics32/graphics32/assets/18141921/623557f8-66ae-49b3-ae7f-1e808a1d039b)

**Closed** 2024-04-06 15:36 UTC
Labels: enhancement

**Comment by lamdalili** [comment] 2024-04-06 19:42
Thanks for your great efforts the second fix works as expected  :+1: 
I tested the first code of `TDashBrush branche` works in some cases in others it fails completely, it seems that  `PolyPolygonFS ` isn't calles at all
here example :

![dash tst](https://github.com/graphics32/graphics32/assets/40634105/059dd337-2bea-4270-934c-2e6573223176)

the second design  in `TCustomBrush-redesign ` is clearer and easier to guess than the previous implementation of the old fix which was narrowly designed to work with `TStrokeBrush, I just have a quick remark about the code of `TDashedBrush.ProcessPolyPolygon`  dashes are always open when passed to the inherited method Closed should be  false  `

https://github.com/graphics32/graphics32/blob/a517ef063bb4063ca4b0b5b03baf55ddccb61c48/Source/GR32_Brushes.pas#L667-L671

as you can see in the figure

![DashedBrush](https://github.com/graphics32/graphics32/assets/40634105/5d629dad-7dad-4b57-8f4a-3d8b9941d0d4)
 
I propose this change :   
```
  if Length(FDashArray) = 0 then
  begin
    Result := inherited ProcessPolyPolygon(Renderer, Points, ClipRect, Transformation, Closed);
  end else
  begin
    Result := nil;
    for I := 0 to High(Points) do
      Result := Result + BuildDashedLine(Points[I], FDashArray, FDashOffset, Closed);

    Result := inherited ProcessPolyPolygon(Renderer, Result, ClipRect, Transformation, False);
  end;
```
My last remark is the current code is supposed to work with `TDashedBrush ` ,  `TStrokeBrush `and  `TSolidBrush`but doesnt guarantee the support of other type of Brushs  , for this it would also be necessary to think about resolving this problem at the level of TRender with multi passes , I think you probably discussed about the subject here https://github.com/graphics32/graphics32/issues/63



the last thing I want to know how to enable Clipper & Angus  utilites , I 've juste enable the symbol  `GR32_OFFSET_CLIPPER` in GR32_VectorUtils but this doesn't work ?


when  comparing  with Firefox broser I get this 

![MosVsGR](https://github.com/graphics32/graphics32/assets/40634105/73b14c0b-cbd0-4d77-8e13-13b170800750)

Svg file  of test 

![DashStroke](https://github.com/graphics32/graphics32/assets/40634105/759874d1-0b62-4a53-a9bb-b408b3911025)

```
 var
  img:TImage32;
  C:TCanvas32;
  Stroke:TDashedBrush;
  dh: TArrayOfFloat;
begin
   img:=TImage32.Create(Self);
   img.AutoSize:=True;
   img.Parent:=Self;
   Img.Bitmap.SetSize(600,400);
   Img.Bitmap.Clear(clWhite32);
   C:=TCanvas32.Create(Img.Bitmap);
   Stroke:= C.Brushes.Add(TDashedBrush) as TDashedBrush;
   Stroke.StrokeWidth := 20;
   Stroke.SetDashArray([30 ,10]);
   Stroke.FillColor := SetAlpha(clRed32,50);
   C.BeginUpdate;
   with C do
   begin
      MoveTo(129, 198);
      LineTo(432, 198);
      LineTo(432, 131);
      LineTo(157, 134);
      LineTo(129, 198);
      EndPath(false);

      MoveTo(198, 61);
      LineTo(198, 309);
      LineTo(263, 309);
      LineTo(263, 20);
      EndPath(false);

      MoveTo(315, 58);
      LineTo(313, 307);
      LineTo(378, 307);
      LineTo(378, 20);
      EndPath(true);
   end;
   C.EndUpdate;
```

**Comment by andersmelander** [comment] 2024-04-06 20:16
> I tested the first code of TDashBrush branche works in some cases in others it fails completely, it seems that PolyPolygonFS isn't calles at all

Yes, that's as-expected with that branch. The **TCustomBrush-redesign** branch should fix that.


> My last remark is the current code is supposed to work with TDashedBrush , TStrokeBrush and TSolidBrushbut doesnt guarantee the support of other type of Brushs , for this it would also be necessary to think about resolving this problem at the level of TRender with multi passes , 

Please explain.


> I think you probably discussed about the subject here #63

I have tried various solutions to the fill-and-stroke problem but I have unfortunately not been able to come up with any good solutions.
If you have any ideas, please share them at #63

> the last thing I want to know how to enable Clipper & Angus utilites , I 've juste enable the symbol GR32_OFFSET_CLIPPER in GR32_VectorUtils but this doesn't work ?

Enabling `GR32_OFFSET_CLIPPER` should be enough.
Try changing `TCustomBrush.RenderPolyPolygon` to also call `PolyPolylineFS` so you can see what is going on:

```Delphi
procedure TCustomBrush.RenderPolyPolygon(Renderer: TCustomPolygonRenderer; const Points: TArrayOfArrayOfFloatPoint;
  const ClipRect: TFloatRect; Transformation: TTransformation; Closed: Boolean);
begin
  UpdateRenderer(Renderer);
  Renderer.PolyPolygonFS(Points, ClipRect, Transformation);

  PolyPolylineFS(TPolygonRenderer32(Renderer).Bitmap, Points, clBlue32, Closed);
end;
```
![billede](https://github.com/graphics32/graphics32/assets/18141921/4cec3290-5c10-4b83-9945-1d7425b3062a)

> when comparing with Firefox broser I get this

Investigating...

**Comment by andersmelander** [comment] 2024-04-06 20:39
| GR32_VectorUtils.Reference | GR32_VectorUtils.Clipper2 | GR32_VectorUtils.Angus |
| ---- | ---- | ---- |
| ![billede](https://github.com/graphics32/graphics32/assets/18141921/b39451b8-7f51-4129-9b23-d40bcff19eee) | ![billede](https://github.com/graphics32/graphics32/assets/18141921/da582964-c762-48f8-846a-e1bcc8d10119) | ![billede](https://github.com/graphics32/graphics32/assets/18141921/d128c1dc-a123-470c-af5c-1dff0e5b5987) |

I don't think this is a problem; It's a corner case with no exact solution. Like the problems in #106. We can keep tweaking the algorithm forever without ever solving all the small quirks.
If you can find a solution that doesn't kill performance you are welcome to give it a go.
Actually, now that I compare the output of GR32_VectorUtils.Reference and GR32_VectorUtils.Angus it looks as if one of the changes suggested in #106 has not been applied.

**Comment by andersmelander** [comment] 2024-04-06 21:25
I just applied one of the changes you suggested in #106 and now the output matches that of GR32_VectorUtils.Angus **exactly**... How about that.

**Comment by lamdalili** [comment] 2024-04-06 22:58
> Please explain.
I am nor sure but as you can see the three mentioned brushs TDashedBrush , TStrokeBrush and TSolidBrushbut  are based on vectors are easy to  draw in any order but i guess this is not possible for other situations you can take a look at `TNestedBrush `there are several consecutive calls to `PolyPolygonFS `and I can guess not all rendreing operations can be deferred, so it is not entirely true to say that the old design is wrong since it remains possible, in the worste case,  that the drawing process uses a temporary buffer and after that alpha component should be corrected.

> Enabling GR32_OFFSET_CLIPPER should be enough.
When I enable the derective and debug BuildPolyPolyLine called in` TStrokeBrush.ProcessPolyPolygon `I am directly at GR32_VectorUtils.Reference and there is no change in the output ...

> I don't think this is a problem; It's a corner case with no exact solution.
I am not worried about that  I know that the basic Grow doesn't generate perfect offsets, for performance reasons the operation is shortened, I just want to see how the production of Clipper looks like.

> Like the problems in #106. We can keep tweaking the algorithm forever without ever solving all the small quirks.

The problem in 106 cannot appear with Clipper it's perfectly handled, if it's present is for other reason as you  showed in the last photos, these irregularities look more like a wraped dash rather offsetting bug.

**Comment by andersmelander** [comment] 2024-04-06 23:37
> I can guess not all rendreing operations can be deferred, so it is not entirely true to say that the old design is wrong since it remains possible, in the worste case, that the drawing process uses a temporary buffer and after that alpha component should be corrected.

Yes. I see your point.

The brush system really is only meant to handle vector operations via TCanvas32. So a nested brush, like for example TGrowBrush, is only meant to contain other vector brushes.
You can misuse the brushes to do pixel operations, like I do in TDotBrush in the Curves examples, but they are not designed for that.

```Delphi
type
  // Draws a single dot at each vertex
  TDotBrush = class(TCustomBrush)
  strict private
    FColor: TColor32;
  private
    procedure SetColor(const Value: TColor32);
  protected
    procedure RenderPolyPolygon(Renderer: TCustomPolygonRenderer; const Points: TArrayOfArrayOfFloatPoint;
      const ClipRect: TFloatRect; Transformation: TTransformation; Closed: Boolean); override;
  public
    constructor Create(BrushCollection: TBrushCollection); override;

    property Color: TColor32 read FColor write SetColor;
  end;

constructor TDotBrush.Create(BrushCollection: TBrushCollection);
begin
  inherited;
  FColor := clWhite32;
end;

procedure TDotBrush.RenderPolyPolygon(Renderer: TCustomPolygonRenderer; const Points: TArrayOfArrayOfFloatPoint;
  const ClipRect: TFloatRect; Transformation: TTransformation; Closed: Boolean);
var
  i, j: integer;
  Bitmap: TCustomBitmap32;
begin
  Bitmap := (Renderer as TPolygonRenderer32).Bitmap;
  for i := 0 to High(Points) do
    for j := 0 to High(Points[i]) do
      Bitmap.PixelFS[Points[i, j].X, Points[i, j].Y] := FColor;
end;

procedure TDotBrush.SetColor(const Value: TColor32);
begin
  if (FColor = Value) then
    exit;
  FColor := Value;
  Changed;
end;
```

> GR32_OFFSET_CLIPPER 

You should be able to see in Delphi if the symbol is defined. The editor should gray out the other units:
![billede](https://github.com/graphics32/graphics32/assets/18141921/f5cf3550-4c45-4124-a242-4990f24fff3a)

**Comment by lamdalili** [comment] 2024-04-07 09:59
Thanks now it works without problem.

**Comment by lamdalili** [comment] 2024-04-08 05:08
`GR32_DEBUG_BRUSH ` was left enabled in the merged code. 

and  the name  `RenderPolyPolygon` is incorrect in TDotBrush example
