### ISSUE TITLE
Incorrect compiler define in GR32_Transforms for 64-bit

### ISSUE THREAD

**Issue by lystakata** [graphics32/graphics32#319] opened 2024-07-16 16:06 UTC
Recently the code was updated in GR32_Transforms.

function DET_2x2_32_ASM and DET_2x2_64_ASM use CPU64 as a compiler conditional. This fails on a 64-bit build and executes the wrong code creating an AV.

Changing to TARGET_x64 fixes the AV.

**Comment by andersmelander** [comment] 2024-07-16 17:10
Reproduced using PerspectiveCorrection example.

**Comment by andersmelander** [comment] 2024-07-16 17:14
As far as I can tell, the CPU64 problem has been there since the functions were introduced in 2012.
Regardless, I'll fix them.

Thanks for the bug report.

**Comment by andersmelander** [comment] 2024-07-16 17:19
Changing `CPU64` to `TARGET_X64` fixes the compiler error but the 64-implementations appear to broken.
![billede](https://github.com/user-attachments/assets/b26e02b9-e16f-40a9-af0a-bd1111e18792)

**Comment by andersmelander** [comment] 2024-07-16 22:55
Fixed in 3dd467d6aff0db749a3a73b04bc60ca416b1995e (I forgot to tag the issue in the commit).

**Closed by andersmelander** 2024-07-16 22:55 UTC
Labels: bug
