### ISSUE TITLE
TBoxKernel not working correctly

### ISSUE THREAD

**Issue by jan-cosmigo** [graphics32/graphics32#209] opened 2022-09-17 11:27 UTC
When using TBoxKernel (nearest neighbour scaling) then the image becomes blurry when upscaling.
Possibly caused by https://github.com/graphics32/graphics32/commit/41cc68ea598d98dc93169064713d074f5a1fc118

**Comment by andersmelander** [comment] 2022-09-17 12:29
I'm unable to reproduce. Can you reproduce with the [Resamplers](https://github.com/graphics32/graphics32/tree/master/Examples/Resampling/Resamplers) example?

This is what I'm seeing with the Resamplers example:
![billede](https://user-images.githubusercontent.com/18141921/190856711-584f7a18-40ea-4cf5-8cf3-b35ba5e079bb.png)
Looks fine to me.

**Comment by jan-cosmigo** [comment] 2022-09-17 16:46
Please find a test project attached that shows the effect I have.
It uses a simple source image and draws its bitmap to another image having a larger size and resampling is done with the TBoxKernel.

[gr32-TBoxKernel-Effect.zip](https://github.com/graphics32/graphics32/files/9592159/gr32-TBoxKernel-Effect.zip)

Desired output:
![image](https://user-images.githubusercontent.com/47713461/190867285-35913968-3b80-404e-a185-565a5aa78fed.png)
Which use an quite old version: https://github.com/graphics32/graphics32/commit/900fdcc3d9fb99bae45cbaa20db9543ebeedf3e1

Output with latest version:
![image](https://user-images.githubusercontent.com/47713461/190867299-775ff54a-fd9c-4990-a45d-e3f969cfe3fb.png)

I just saw that there is also a TNearestResampler class. I could use this instead. I always used TKernelResampler and then added the appropriate Kernel for what I want to do.

By the way... the library is great. Keep up the good work.

**Comment by andersmelander** [comment] 2022-09-17 18:54
Yes, I see it now. The cause of the problem is commit 70652d3e9f064a8f842205c440eeee0dae53b736 by @rmesch.
I'll have to look into why it's a problem.

Regardless, if `TNearestResampler` works satisfactory you really should use that instead as that is the fastest of them all.

**Comment by andersmelander** [comment] 2022-10-05 22:11
Was fixed by 784e1dbe74398a6c3a99ff3788f50bc79ea79e69

**Closed by andersmelander** 2022-10-05 22:11 UTC
Labels: bug
