### ISSUE TITLE
Adding GR32 to a custom design time package raises IDE error with Delphi 11.3

### ISSUE THREAD

**Issue by sojimathew** [graphics32/graphics32#256] opened 2023-06-15 12:38 UTC
While updating my code base to Delphi 11.3, I got the latest graphics32  packages. But then I started to get an av while closing Delphi IDE. After excluding all the suspected packages, I narrow it down to GR32. I made a simple design time package application and used GR32 in it and then I get Access violation at address 618E8D0C in module 'rtl280.bpl'. Read of address 6ABF28BC. while closing the IDE.

I am attaching the sample to reproduce this issue:
[Delphi 11 Package Test.zip](https://github.com/graphics32/graphics32/files/11757523/Delphi.11.Package.Test.zip)

**Comment by andersmelander** [comment] 2023-06-15 13:10
Reproduced.

- Installing and then uninstalling does not reproduce the error.
- Installing and then closing Delphi reproduces the error.

**Comment by andersmelander** [comment] 2023-06-15 13:24
Call stack:

```
rtl.System._IntfClear(???)
:4fc68960 @IntfClear + $10
rtl.System._FinalizeArray($40A60928,$CF9CFA8,20)
rtl.System.Generics.Collections.TListHelper.InternalDeleteRangeManaged(0,20)
rtl.System.Generics.Collections.TListHelper.InternalSetCountManaged(0)
:4fcdd70f TListHelper.InternalSetCountManaged + $3B
rtl.System.TObject.Free
GR32_R.GR32.ImageFormats.TImageFormatManager.Destroy
rtl.System.TInterfacedObject._Release
rtl.System._IntfClear(???)
:4fc68963 @IntfClear + $13
rtl.System.FinalizeUnits
rtl.System._PackageUnload(???,???)
:0c0a1912 ; C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\GR32_D280.bpl
:1fa50d36 coreide280.@Pakload@TPackage@InternalUnload$qqro + 0x22
:00467896 ; D:\Development\Embarcadero\Studio\22.0\bin\bds.exe

```

**Comment by andersmelander** [comment] 2023-06-15 15:26
The problem is caused by the use of [`{$WEAKPACKAGEUNIT}`](https://docwiki.embarcadero.com/RADStudio/Alexandria/en/Weak_packaging) in the image format units; The image formats are being registered (into the image format manager) both by the Graphics32 design-time package and by your design-time package via their reference to the GR32 run-time package. The image format manager lives in the Graphics32 run-time package so we have two design-time packages that each register their own copies of the image format objects in the shared image format manager.
It should be noted that image format objects are registered at initialization but they are, by design, never unregistered.

This becomes a problem when the packages are unloaded during IDE shutdown. First, one design-time package is unloaded and the run-time package reference count is decremented (to one). Then, when the other design-time package is unloaded, the run-time package reference count becomes zero and its finalization is executed before it is unloaded.
The finalization destroys the image format manager which in turn clears the image format list and this is where the error occurs; Half of the image format objects resided in the first design-time package which has already been unloaded and therefore we get an access violation. You can see in the stack dump that there are 20 image formats registered instead of the 10 that should have been registered.

The reason `{$WEAKPACKAGEUNIT}` was used was so the run-time package didn't have to _explicitly_ include the individual image format units. I'll undo that.
However, that's only half the problem fixed because if another design-time package registers its own image format then we will have the dangling image format object pointer again. To fix that I'll have to add support for unregistering image format objects and update the individual image formats to do so.

**Closed** 2023-06-15 17:04 UTC
Labels: bug
