### ISSUE TITLE
Canvas32 Path looking strange

### ISSUE THREAD

**Issue by ThomasNeumann** [graphics32/graphics32#45] opened 2019-01-03 08:04 UTC
![stange](https://user-images.githubusercontent.com/37294402/50627898-ed464700-0f35-11e9-89f0-5f00d077e12b.png)

```
Procedure DoPolyLine(const pfad: GR32_Paths.TFlattenedPath;
                           const data: TLineData;
                           const add:  boolean);
var maxl: cardinal;
    i:    cardinal;
begin
  if ( Assigned(pfad) and ( Length(data) > 1 ) ) then begin
    maxl:= High(data);
    if add then
      pfad.MoveTo(data[0])
    else
      pfad.LineTo(data[0]);
    for I := 1 to maxl do pfad.LineTo(data[i]);
  end;
end;
```

With some combinations of the strokewidth and the difference on x axis I get a strange looking graph (see upper trace), while different x spacing works perfect (lower trace)

**Comment by ThomasNeumann** [comment] 2019-01-03 15:13
![strange2](https://user-images.githubusercontent.com/37294402/50644896-75e2d880-0f72-11e9-8c60-b0152824743f.png)
Noch ein Beispiel...

**Comment by CWBudde** [comment] 2019-01-03 16:05
The code and the issue is still a bit vague. Especially without giving more information about the type and the settings of the renderer. For example the fillmode could be interesting. It looks like the fill mode is some sort of alternating the filling. Try to set it to pfWinding if not already done.

Also try if other renderers (such as AggLite) has the same issue.

Last but not least it would help if the code example could be more verbose so that we can reproduce the issue more easily.

**Comment by ThomasNeumann** [comment] 2019-01-04 11:13
Preparation of the canvas32

`Procedure InitCan32(var can32: TCanvas32);
begin
  if (Assigned(can32)) then begin
    can32.Brushes.Clear; //Erstmal..
    can32.Brushes.Add(TStrokeBrush);
    can32.Brushes.Add(TSolidBrush);
    //Configure Brushes
    (can32.Brushes[0] As TStrokeBrush).FillMode:=      pfWinding;
    (can32.Brushes[0] As TStrokeBrush).JoinStyle:=     jsRound;
    (can32.Brushes[1] As TSolidBrush).FillMode:=       pfWinding;
  end;
end;`
Setting Colors and width
` if assigned(can) and (length(data) > 0) and (displayCount > 0) and
        (can.Brushes.Count > 1) then begin
        (can.Brushes[0] as TStrokeBrush).StrokeWidth:=   swPaint;
        (can.Brushes[0] as TStrokeBrush).FillColor:=     color;
        (can.Brushes[1] as TSolidBrush).FillColor:=      SetAlpha(color, GuiAktuell.GetAlfa);`
Show the trace
` endl:= high(aLine);
          (can.Brushes[0] as TStrokeBrush).Visible:= TRUE;
          (can.Brushes[1] as TSolidBrush).Visible:=  FALSE;
          can.Path.Clear;
          can.Path.BeginPath;
          DoPolyLine(can.Path, aLine, False);
          Can.Path.EndPath;`

**Comment by CWBudde** [comment] 2019-01-04 12:58
Can you please try it with the AggLite renderer like this:

```
uses
  GR32_PolygonsAggLite;

...
  can32.Renderer := TPolygonRenderer32AggLite.Create(can32.Bitmap);
...
```

If the issue is not present with this renderer than it's likely to be an issue of VPR. If it is still present than it's more likely to be an issue with your code.

**Comment by CWBudde** [comment] 2019-01-04 13:03
One further note: While the code you provided might be better for legability, it is not optimal for the performance, especially since the offset between the points is equal spaced. Given this fact you can translate the input points to the points needed for the renderer in a more compact way (using BuildPolyPolyLine). This might also be useful to find why and where the current code fails...

**Comment by Jens01** [comment] 2019-01-04 13:38
Crosspostings: https://www.delphipraxis.net/199181-graph-mit-graphics32-darstellungsproblem.html#post1422626

**Comment by ThomasNeumann** [comment] 2019-01-04 14:21
Hi,
the problem remains with AggLite. 
Tried PolyLineFS using can.bitmap, which yields the exactly the same result (using the same paramters. The graphic varies with the joinstyle selected, but remains erratic.

Tomy

**Comment by ThomasNeumann** [comment] 2019-01-04 15:36
Hi,
did a small pop (proof of problem :-) package.
[DrawTest32.zip](https://github.com/graphics32/graphics32/files/2727514/DrawTest32.zip)
Width 1, Random Y 60 and X spacing 0.33 looks also strange

**Comment by CWBudde** [comment] 2019-01-04 17:00
Thanks for the code, I already reduced it even further and I think I already got an idea what happened wrong there. However, I'm still not sure whether it is really wrong or somehow by design.

For now you can get rid of this by decreasing the MiterLimit to about 0.1 (default is 4). It seems that the MiterLimit is dependent on the y-resolution for some reason. This should - as far as I understand - not be the case, but the points are pretty dense and it might not have been tested well so far.

In your particular case the following lines:

    Poly2 := BuildPolyLine(ALine, 0.1 * tbWidth.Position, jsRound, esButt, 0.1);
    PolygonFS(PaintBoxShow.Buffer, Poly2, clYellow32, pfWinding, nil);

should do the trick (the type of Poly2 is TArrayOfFloatPoint). The problem happens already in the BuildPolyLine, but is exposed later in the PolygonFS(...) function.

As I'm not sure whether I will have time to investigate this problem at the moment, I'd like to advise my future-me to look into the grow function.

Eventually I will close it as by-design in the future.

**Comment by ThomasNeumann** [comment] 2019-01-04 21:54
@CWBudde Thank you very much for your investigation. The solution will work for me. 
It's up to you to close this issue ( This issue indicates that my knowledge of rendering is too low to decide if this behaviour is a bug or a feature).

**Comment by CWBudde** [comment] 2019-01-05 10:51
In theory, with round joints the miter limit should not be used. However, it seems it is used in a corner case where the 'angle is concave'. Since I haven't wrote the code in the first place, I don't know what it means to get a concave angle. It just seem to happen quite often.

However, it needs a separate issue to solve this problem (if it is solvable at all). So I close this right now and open a new issue for it.

**Closed by CWBudde** 2019-01-05 10:51 UTC
