### ISSUE TITLE
FPC compatibility TResourceType

### ISSUE THREAD

**Issue by faludiz** [graphics32/graphics32#229] opened 2023-04-01 16:18 UTC
Pls change `{$ifndef FPC}` to `{$ifdef FPC}`
https://github.com/graphics32/graphics32/blame/8ce9b8614218264b791a2d0516c9d075801bf825/Source/GR32.pas#L674

**Comment by andersmelander** [comment] 2023-04-01 16:25
I'm assuming you're using FPC, because the declaration is correct with Delphi. The problem is that I forgot to include the LCLType unit for FPC.

I've already changed this in another branch to:
```
{$ifndef FPC}
  TResourceType = PChar;
{$else FPC}
  TResourceType = LCLType.TResourceType;
{$endif FPC}
```
but I'll merge that particular change into the master branch since it'll probably be a while before the other branch is merged.

**Closed** 2023-04-01 16:29 UTC
Labels: bug

**Comment by faludiz** [comment] 2023-04-01 16:55
I don't have Delphi, but FPC needs **type** keword before the definition

```pascal
{$ifndef FPC}
  TResourceType = PChar;
{$else FPC}
type
  TResourceType = LCLType.TResourceType;
{$endif FPC} 
```

I think maybe it would be better to put the whole thing a few lines down in the type definitions

**Comment by andersmelander** [comment] 2023-04-01 18:09
> I think maybe it would be better to put the whole thing a few lines down in the type definitions.

Yes, that's where it is now (commit 82991a5ba34815b7cf1487937ea455ae0ca49a95 in the master branch):

```
type
  TPixelCombineEvent = procedure(F: TColor32; var B: TColor32; M: Cardinal) of object;
  TAreaChangedEvent = procedure(Sender: TObject; const Area: TRect;
    const Info: Cardinal) of object;

  TCustomResampler = class;

  TCustomBackend = class;
  TCustomBackendClass = class of TCustomBackend;

{$ifndef FPC}
  TResourceType = PChar;
{$else FPC}
  TResourceType = LCLType.TResourceType;
{$endif FPC}

  { TCustomBitmap32 }

  TCustomBitmap32 = class(TCustomMap)
```

Are you seeing something else?

**Comment by faludiz** [comment] 2023-04-02 08:40
thx
