### ISSUE TITLE
AddRoundedJoin inserts a miter join

### ISSUE THREAD

**Issue by CWBudde** [graphics32/graphics32#47] opened 2019-01-05 10:56 UTC
If the user decides to use round joins, the joints should be round indeed. However, in case of 'angle is concave' (<- comment from the code), a miter joint is used instead.

While this works well for low miter limits, it does not for high miter values. In this case a sharp spike ruins the visual appearance.

This issue relates to issue #45 as it is the reason for the odd results.

**Comment by meanderix** [comment] 2019-01-05 11:18
Just chiming in on this one. I think the reasoning behind the original implementation was that corners pointing outwards would be rounded, whereas corners pointing inwards (hence the term "concave", as in "concave polygon"), would not be rounded. I don't remember if I borrowed this code, or if the original Grow() function was partially rewritten to support different join styles.

Anyway, this might need to be revised. I fully support the idea of using rounded corners even for inward pointing angles.

**Comment by CWBudde** [comment] 2019-01-05 11:40
Thanks for chiming in, I was already thinking about contacting you here as I don't know much about that code, especially as it seems to be quite well optimized already.

My idea to solve this for now would be to add another procedure like 

```
  procedure AddSimpleMitered(const X1, Y1, X2, Y2: TFloat);
  begin
    AddPoint(Delta * X1, Delta * Y1);
    AddPoint(Delta * X2, Delta * Y2);
  end;
```

which is called instead and implies a miter limit of 0. This way it's still not perfectly round, but doesn't introduce these spikes as found in issue #45.

**Comment by AngusJohnson** [comment] 2019-04-03 03:35
> I think the reasoning behind the original implementation was that corners pointing outwards would be rounded, whereas corners pointing inwards (hence the term "concave", as in "concave polygon"), would not be rounded. 

This is what's required for milling and 3D printing software. There, the cutting tool invariably creates rounded vertices at convexities (the radius will depends on the size of the cutting tool), but at concavities the cutting tool can and does generate sharp vertices.

Anyhow, while I agree that it doesn't look as pretty, the math involved in generating rounded concave joins would be considerably more complicated, and hence considerably slower to construct too.

**Comment by AngusJohnson** [comment] 2019-04-03 06:30
Well rounding inner joins isn't too difficult _mostly_, but as is so often the case, it's the edge cases that cause most of the headaches. 

You cans see here that when there is a deep concavity with edges very close relative to the offset delta, the offsetting balloons outside where it should be...  
![offset_round](https://user-images.githubusercontent.com/5280692/55457436-9ab02000-5635-11e9-9b9e-5ab67ad69b68.png)

**Comment by AngusJohnson** [comment] 2019-04-04 02:36
OK, I've created a working solution but as I mentioned above, addressing very narrow concavities requires a _lot_ of code, and even then it doesn't always produce a perfect solution and I'm not sure this added complexity is justified. 

Having said that, the existing Grow algorithm doesn't produce entirely satisfactory results either when 'growing' polygons with narrow concavities, as demonstrated in the image below...

![offset_round](https://user-images.githubusercontent.com/5280692/55525738-f7671580-56dd-11e9-9a4e-9c33bd8e3298.png)

**Comment by AngusJohnson** [comment] 2019-04-04 13:12
I've tidied this up quite a bit and it's not too bad now (see attached). If there's enough interest it would be easy to create another TJoinStyle (eg jsRound2) to provide this alternative rounding style. However, the Grow function still needs quite a bit more work IMHO to make it easier to understand and maintain. Also, the alternative GR32_Clipper.InflatePaths() function I would suggest produces many fewer artifacts.

[GR32_VectorUtils.zip](https://github.com/graphics32/graphics32/files/3043528/GR32_VectorUtils.zip)

**Comment by andersmelander** [comment] 2019-04-05 11:02
You've mixed up the files from two different demo projects but I managed to get it rolling anyway.
I'll try to provide some feedback later although this isn't really my area of expertise.

**Comment by AngusJohnson** [comment] 2019-04-05 11:32
> You've mixed up the files from two different demo projects

Yeah, was about to upload GR32_VectorUtils.pas, when I figured (late in the evening) that a simple demo would also be appreciated :). The code is still ugly as is similar offsetting code in GR32_Clipper that I've spent much of the day rewriting.

**Comment by andersmelander** [comment] 2019-04-05 13:34
Looks good.
I don't know what the expected result is for self-intersecting polygons but at least it's consistent.
![billede](https://user-images.githubusercontent.com/18141921/55631387-2fdb2200-57b8-11e9-9bf9-c3bdad6c7657.png)
I guess those could be handled beforehand by preprocessing the polygons somehow.

Once this is implemented, will there still be an option to have only the convex joins rounded?

Wrt. to code style, could you be persuaded to add a space after "//" to make you comments more readable?

**Comment by AngusJohnson** [comment] 2019-04-05 13:51
> I don't know what the expected result is for self-intersecting polygons

I suggest documenting that Grow() returns undefined results when passed self-intersecting polygons. 

> Once this is implemented, will there still be an option to have only the convex joins rounded?

I'd be happy to implement it if there's interest though I would most definitely keep the existing option too. As I've suggested above, this new rounding join style could be designated jsRound2 . 

And spaces after double slashes? Never ;)))

**Comment by andersmelander** [comment] 2019-04-05 15:28
> I suggest documenting that Grow() returns undefined results when passed self-intersecting polygons.

That's fine.
Do we have any methods in stock to calculate the outer polygon from a potentially self-intersecting polygon?

> I'd be happy to implement it if there's interest

There is. For some use cases it produces a more "natural" output since, as you mentioned, it emulates a milling tool (or a thick stroke).

> this new rounding join style could be designated jsRound2

or `jsRounder` :-)

> using the full radius shortens too much

Agree.

>  spaces after double slashes? Never ;)))

Yeah. All this white space slows the compiler down :-)

**Comment by andersmelander** [comment] 2019-04-05 17:40
I've tried moving `StripSelfIntersections()` so it's applied before `Grow()` is called. If my assertion that it returns the outer polygon as the first element is correct, only the outer polygon should grown. Well, that doesn't work:
![billede](https://user-images.githubusercontent.com/18141921/55645496-07afeb00-57d9-11e9-968e-d04d443ef68c.png)

Even for non-intersection polygons there are occasional problems:
![billede](https://user-images.githubusercontent.com/18141921/55645636-5d849300-57d9-11e9-8922-cb9f51c66f0f.png)
I guess there's a problem when two rounded corners intersect.

**Comment by AngusJohnson** [comment] 2019-04-05 19:58
> Even for non-intersection polygons there are occasional problems

I will never use GR32_VectorUtils.Grow() because it will always be problematic, even with relatively simple polygons. As I said above ...
> GR32_Clipper.InflatePaths() function I would suggest produces many fewer artifacts.

In fact my recommendation is to delete Grow.

**Comment by AngusJohnson** [comment] 2019-04-05 20:26
Also, I'm modified the code in GR32_Clipper.InflatePaths()) so that MiterLimit will allow controls over the relative radius of concave rounding. I'll upload the code later, I'm almost finished doing a major rewrite.
 So ...
MiterLimit = 1 -- concave rounding will (where possible) be the same radius as convex rounding;
MiterLimit = 2 -- concave rounding will be 1/2 the radius of convex rounding
MiterLimit = 4 -- concave rounding will be 1/4 the radius of convex rounding
etc ...
![grow1](https://user-images.githubusercontent.com/5280692/55654217-838f4f00-583c-11e9-9ea1-fec44e1305f8.png)
![grow2](https://user-images.githubusercontent.com/5280692/55654214-82f6b880-583c-11e9-94a2-6af55a569938.png)
![grow4](https://user-images.githubusercontent.com/5280692/55654215-838f4f00-583c-11e9-9548-654c5d324e00.png)

**Comment by andersmelander** [comment] 2019-04-05 22:13
> In fact my recommendation is to delete Grow.

I've only ever used `Grow()` to construct filled, rounded rectangles and it did that well enough. 
If `TClipperOffset` can do everything that `Grow()` does and doesn't have the same problems then I can't see why we should keep it. I do think we should try to maintain backward compatibility though. So I guess a reimplementation of `Grow()` that internally uses `TClipperOffset`? FWIW `TClipperOffset` so far has handled everything I've thrown at it without problems.

Back to my question about `StripSelfIntersections()`: I have no idea of what it does but I can see now that it **doesn't** return the outer polygon. So just out of curiosity: Do we have a function that does return an outer polygon?

**Comment by AngusJohnson** [comment] 2019-04-05 22:29
>  So I guess a reimplementation of Grow() that internally uses TClipperOffset

That's very easy to do.

> Back to my question about StripSelfIntersections(): I have no idea of what it does

It was intended to convert self-intersecting polygons into multiple polygons. It's in a sample unit that I wrote hastily (as it was quite late) a couple of nights ago, so I'm not entirely surprised if it isn't performing as intended.

**Comment by andersmelander** [comment] 2019-04-06 18:05
Minor glitch produced by the code you just committed:
![billede](https://user-images.githubusercontent.com/18141921/55673302-93437d80-58a6-11e9-9f23-56621c8b43de.png)

**Comment by AngusJohnson** [comment] 2019-04-06 18:54
> And the self-intersection removal doesn't seem to always work

![clippping](https://user-images.githubusercontent.com/5280692/55673868-17baee00-58f1-11e9-8db0-956095f16f7d.png)

:)

**Comment by andersmelander** [comment] 2019-04-06 19:08
Not sure I got the meaning there... Are you saying there's no intersection?

**Comment by AngusJohnson** [comment] 2019-04-06 19:18
> Are you saying there's no intersection?

That's what I'm saying.

**Comment by andersmelander** [comment] 2019-04-06 19:32
Then why isn't the joint rounded?
Either the polygon is self-intersecting or there's two polygons. According to your source neither should be possible if `GeneratePolygon()` does what it says it does.

I have made a small change to you demo so that it displays the value of RandSeed in the form Caption. That way I can make it reproduce a particular polygon by restoring RandSeed to a given value.
Here's one: 524963136
And another with no self-intersection but a joint that isn't rounded: -982965537

**Comment by andersmelander** [comment] 2019-04-06 19:53
Am I correct in observing that there still is a problem when two rounded corners intersect?
![billede](https://user-images.githubusercontent.com/18141921/55674501-ef61ce00-58b5-11e9-8c3a-31450f04e125.png)
![billede](https://user-images.githubusercontent.com/18141921/55674517-14eed780-58b6-11e9-86de-7936d4a829a3.png)

**Comment by AngusJohnson** [comment] 2019-04-06 22:00
> Then why isn't the joint rounded?

Each of those joins would have been rounded but the rounding would be lost when the overlapping stuff is removed (clipped).  Without any clean up it would look like this ...
![clippping](https://user-images.githubusercontent.com/5280692/55675800-1f878c00-590b-11e9-864c-87888df31edb.png)

I understand that this isn't what you'd like to see, but to round where cleanup clipping has created new (pointy) vertices I think would be enormously complicated.

**Comment by andersmelander** [comment] 2019-04-06 22:26
OK, so I'm guessing the original polygon was self-intersecting. Your post processing swapped some vertices to make it into a weakly-simple polygon. Since some weakly-simple polygons can't be grown without producing a self-intersecting polygon there's a problem and I guess that's what we are seeing.

IMO we should:
- Document that "growing" a self-intersecting or weakly-simple polygon produces funky results.
- Provide a function to test for self-intersection - including weakly-simple.
- Provide a function to construct an outer polygon from a self-intersecting or weakly-simple polygon.
With these tools a user (and your demo) would have the ability to reliably "grow everything".
I looked into what it would take to write these function and while the naive implementations are fairly simple they would also performs horribly. The fast solutions are too complicated for the limited time I have to spare ATM (just quit my job, waiting for the new one to start).

With regard to the intersecting rounded corners I think it's a fair limitation that they aren't handled "perfectly", but I think it would be best if we can avoid the tiny spike I've seen when a concave and a convex corner meet.

**Comment by AngusJohnson** [comment] 2019-04-07 04:11
> Provide a function to test for self-intersection - including weakly-simple.

A function for self-intersection is easy, it's already done. However, what do you mean by "weakly-simple"? I'll assume you mean polygons with vertices or edges touching other edges or vertices in the same polygon.

> Provide a function to construct an outer polygon from a self-intersecting or weakly-simple polygon.

I'll assume by this you mean breaking up polygons in a way that makes it easy to inflate without spoiling join rounding. Firstly, deciding how/where to split these isn't simple. But regardless, this won't always prevent offset polygons from clipping others, and even themselves ...
![clippping4](https://user-images.githubusercontent.com/5280692/55678509-7c506a00-593e-11e9-86e2-2154ae31912f.png)
![clippping3](https://user-images.githubusercontent.com/5280692/55678512-85d9d200-593e-11e9-8c74-5e1b30911844.png)

> I think it would be best if we can avoid the tiny spike I've seen when a concave and a convex corner meet.

That at least is achievable :).

**Comment by andersmelander** [comment] 2019-04-07 11:07
> what do you mean by "weakly-simple"

>>  I'll assume you mean [...]

Yes. [Here's a good explanation :-)](http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Classes/Clipper/Properties/StrictlySimple.htm)

>>   Provide a function to construct an outer polygon from a self-intersecting or weakly-simple polygon.

> I'll assume by this you mean breaking up polygons

I mean breaking up a complex polygon and returning the union of the resulting polygons. This will eliminate holes and "weak holes". I'm aware that this will only solve a subset of the problems and I'm not entirely sure that it's worth the effort; I'm just trying to imagine possible problem cases and what I would intuitively expect the result to be.

**Comment by AngusJohnson** [comment] 2019-04-07 11:44
> Yes. Here's a good explanation :-)

LOL. Touché!

**Closed** 2019-04-12 05:47 UTC
