### ISSUE TITLE
(GR32_Transforms.pas) TPointF.Create don't exists in Lazarus 2.0.6

### ISSUE THREAD

**Issue by gwiethaus** [graphics32/graphics32#119] opened 2019-12-12 18:20 UTC
Sorry about my English
I found that it is not compiling and installing on Lazarus 2.0.6.
In the library: \Source\GR32_Transforms.pas
I verified that

` // center / focal point relative to which all (un) distortions are calculated`
`   FFocalPoint: = TPointF.Create (`
`     (SrcRect.Right + SrcRect.Left) / 2,`
`     (SrcRect.Bottom + SrcRect.Top) / 2);`

It does not exist in Lazarus, but it does exist in Delphi 10.3.2. In Delphi it compiled and installed normally.

This code snippet is within procedure TRadialDistortionTransformation.PrepareTransform;

There are other parts of the component that need adjustment.

**Comment by andersmelander** [comment] 2019-12-16 19:52
Duplicate of #113

**Closed by andersmelander** 2019-12-16 19:52 UTC
Labels: bug, duplicate
