### ISSUE TITLE
PNG images are displayed in wrong colors.

### ISSUE THREAD

**Issue by DumTiDum** [graphics32/graphics32#159] opened 2021-06-08 15:23 UTC
I took the changes (from April) and noticed that the colors of the png images are now mixed up. 
On Windows, using gr32 and gr32png.

It looks likes somwhere in the code rgb is used to load the image, but bgr to write it. (Or vv.).

**Comment by DumTiDum** [comment] 2021-06-08 16:12
I changed ConvertColorNonInterlacedTrueColorAlpha8bit in GR32_PNG.pas
to
    Dst^.B := MappingTable[Src^.R];
    Dst^.G := MappingTable[Src^.G];
    Dst^.R := MappingTable[Src^.B];
    Dst^.A := Src^.A;

which seems to help, however, I am not sure that this is/was the rootcause. I expect that to be somewhere else in gr32.

**Comment by andersmelander** [comment] 2021-06-08 16:20
Your change is obviously just a work around :-)

Assuming the problem is in Graphics32 and not in GR32PNG, it would help if you could determine what commit broke it for you. It should be reasonably quick to a binary search from the last version that worked to the latest version.

**Comment by DumTiDum** [comment] 2021-06-08 16:31
Ha, yes, that's where I started to look for. Unfortunately I don't know what version I have, I got it some time ago.

The list of differences is big....
![changes](https://user-images.githubusercontent.com/29923741/121223341-b6538880-c887-11eb-86b5-5d547e71dde1.png)

**Comment by andersmelander** [comment] 2021-06-08 16:35
Oh... I see.
Well I think even if you started with a three year old version a binary search should be relatively quick regardless.

**Comment by andersmelander** [comment] 2021-06-08 16:41
If you look in `GR32_Compiler.inc` of the old version what is the latest version of Delphi that it mentions?

**Comment by CWBudde** [comment] 2021-06-09 03:40
The code in the GR32PNG repository contains a unit test. Can you please run it and check which tests fail for you? Some of the tests require a visual feedback, especially to ensure that the colors do match. You can switch between GR32PNG and the Delphi default PNG decoder. There are a few corner cases where the output does not match 100%, but the colors should be correct.
At least on my side it works like a charm.

**Comment by DumTiDum** [comment] 2021-06-10 09:02
@andersmelander 

old version: COMPILERRX2  - Delphi RX2 (10.2 Tokyo)

@CWBudde 
I'll try.

**Comment by andersmelander** [comment] 2021-06-10 09:53
> old version: COMPILERRX2 - Delphi RX2 (10.2 Tokyo)

Okay, so that makes your old version no older than 7-jun-2017. There's 2446 commit between then and now so you should be able to find the commit that broke it in no more than 12 attempts.

**Comment by DumTiDum** [comment] 2021-06-10 09:56
Alright.

**Comment by andersmelander** [comment] 2021-06-10 10:14
@DumTiDum Did you mean to close this issue or did you press the wrong button?

**Comment by DumTiDum** [comment] 2021-06-11 21:57
Yes.

**Comment by CWBudde** [comment] 2021-06-11 22:00
Are the wrong colors throughout all tests or are they limited to specific tests?

**Comment by andersmelander** [comment] 2021-06-11 22:22
Yes, you meant to close it or Yes, you pressed the wrong button?

**Comment by DumTiDum** [comment] 2021-06-11 22:32
@CWBudde I stopped after 50 times clicking, I'ld say, all of them fail.

**Comment by CWBudde** [comment] 2021-06-11 22:35
Is this with GR32 v1.9x or with the newer version 2.0 alpha?
This said, I can't reproduce this with either combination.

**Comment by CWBudde** [comment] 2021-06-11 22:37
Would you mind to go back to a revision from something earlier, like end 2020 and check whether it happens there as well?!?

**Comment by DumTiDum** [comment] 2021-06-11 22:53
I'm using lazarus/fpc. I have PUREPASCAL set in GR32_PngCompilerSwitches. I just downloaded both the latest gr32 and gr32_png, completely new folder, new project. And there the unit-test also fails.

I already tried going back to a few earlier versions, no succes.

If it works on your end, then I'm happy to use my workaround. Maybe it only happens with fpc.

**Comment by CWBudde** [comment] 2021-06-11 22:57
Oh sorry, I missed the fact that you used it with FPC / Lazarus. It would have been nice to mention this in the first place. As the moment we do not have an active maintainer for Lazarus.

I did some housekeeping at the beginning of this week, but not got far due to other projects. In this case I think it could be related to the backend. It would be interesting to see what backend is affected. Is it only the LCL Windows backend or GTK backends as well. In this case the workaround might be different depending on the platform.

**Comment by DumTiDum** [comment] 2021-06-12 10:54
@CWBudde  Agree, I apologize, I should have mentioned that directly.

**Comment by CWBudde** [comment] 2021-06-29 10:03
In unit GR32_Compiler.inc there is probably a define for RGBA_FORMAT, could you check whether this is set properly on your system? If not, it would make sense to set it as it should be set by default for FPC

**Comment by CWBudde** [comment] 2021-07-03 11:29
I have changed quite a bit in the GTK backend. After the changes, I have tested this with the GR32_PNG library. It seems to show correct colors. Can you please confirm whether this is still an issue on your side? If so, please let me know what backend you are using (Windows, GTK, Carbon, CustomDrawn, etc.).

**Comment by andersmelander** [comment] 2021-12-14 01:55
Closing due to inactivity

**Closed by andersmelander** 2021-12-14 01:55 UTC
Labels: bug
