### ISSUE TITLE
Polygon grow using Clipper2 very very slow

### ISSUE THREAD

**Issue by ThomasNeumann** [graphics32/graphics32#284] opened 2024-02-29 18:42 UTC
Hi,
I have this code

```Delphi
procedure DrawLineThickR( const daten: TArrayOfFloatPoint;
                          const tw: double;
                          const wo: TBitmap32;
                          const cLine: TColor32;
                          const shadow: Boolean;
                          const shadowY: Single); inline;
var
  daLa:   TArrayOfFloatPoint;
  ida:        TArrayOfFloatPoint;
  FRenderer: TPolygonRenderer32VPR;
  endl: Integer;
  tl:   Int64;
begin
  tl:= TimeGetTime;
  FRenderer:= TPolyGonRenderer32VPR.Create(wo);
  if Assigned(FRenderer) then begin
      if Shadow And ( Length(daten) > 2 ) then begin //at least three values in a row...
           SetLength(ida, Length(daten) + 2);
           ida[0].X := daten[0].X;
           ida[0].Y := shadowY;
           winApi.windows.CopyMemory(@ida[1], @daten[0], Length(daten) * siDo);
           endl := High(ida);
           ida[endl].X := daten[High(daten)].X;
           ida[endl].Y := shadowY;
           FRenderer.Color:=  SetAlpha(cLine, GuiAktuell.GetAlfa);
           FRenderer.PolygonFS(ida);
    end;
    daLa := GR32_VectorUtils.BuildPolyLine(daten, tw, jsRound, esRound, 0.1);
    FRenderer.Color:= cLine;
    FRenderer.PolygonFS(daLa);
    FRenderer.Free;
  end;
  errorM.LogError(IntToStr(timeGetTime - tl));
end;
```
With older version of Graphics32 (the one I have for test is from October 2023) it reports about 20ms, with the current version it reports (and takes) approx 3 seconds!
I'm using 10.3 on a win64 machine, the issue occurs both with 32Bit and 64Bit exes.
Furthermore, I hat to put the /source directory of Graphics32 at the top of the project's seach path, otherwise the IDE reports 'jtBevel not defined' :-(

`jtBevel     = Clipper.Offset.jtBevel;`

**Comment by andersmelander** [comment] 2024-02-29 19:05
My guess is that you have and old version of [Clipper2](https://github.com/AngusJohnson/Clipper2) in your search path.

I recently updated the version of Clipper used in Graphics32 to a newer version (1.3.0) and changed the `BuildPoly*Line` and `Grow`functions to use the features provided by Clipper. See: 3b309411faf8c5aa0c87e1bc49d88e04d01ca1f3

You can revert to the old implementation by undefining `USE_CLIPPER_GROW` and defining `USE_OLD_GROW` in `GR32_VectorUtils.pas`. However, the plan is to eventually retire the old implementation.

I'm curious if you can reproduce the performance problem with the `Examples\Drawing\Benchmark` example (All tests, TPolygonRenderer32VPR renderer).

**Comment by ThomasNeumann** [comment] 2024-02-29 22:48
Thanks. Its very strange. I found that the svgimage unit, which I also use, uses img32 which also contains contains clipper units.

So I reverted to previous version of Graphics32 and will investigate further.

**Comment by andersmelander** [comment] 2024-02-29 23:03
You could ask @AngusJohnson to update the Clipper2 in Image32. As far as I can tell the _current_ version of Image32 uses a Clipper2 from mid July 2023 (which is probably too old for Graphics32 because of breaking changes in Clipper2) and svgimage again might be using an older version of Image32 which will then use an even older version of Clipper2.

**Comment by ThomasNeumann** [comment] 2024-02-29 23:09
Well, just update to most current version of svgimagelist, which contains a more up to date version of image32. So the compiler stops complaining, and the drawing now just takes 300 ms.

**Comment by andersmelander** [comment] 2024-02-29 23:21
That's still an order of magnitude slower which IMO is unacceptable.

Also, if you could use `TStopWatch` instead of `timeGetTime` and measure 100 or 1000 iterations it would get us a better picture of the performance.

Of course, if _you_ are satisfied that the problem is resolved, you're welcome to close it.

**Comment by ThomasNeumann** [comment] 2024-02-29 23:43
Hi, I agree that it is not acceptable, but I think it's not a Graphics32 issue.

**Comment by ThomasNeumann** [comment] 2024-03-01 15:51
Well, had to reopen it. Did some tests today, using this code:
```
unit Unit1;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants,
  System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, GR32_Image, GR32, Vcl.ExtCtrls;

type
  TForm1 = class(TForm)
    pbTest: TPaintBox32;
    Panel1: TPanel;
    procedure pbTestPaintBuffer(Sender: TObject);
    procedure Panel1Click(Sender: TObject);
  private
    { Private-Deklarationen }
    fpa: TArrayOfFloatPoint;
    Procedure InitArray;
  public
    { Public-Deklarationen }
  end;

var
  Form1: TForm1;

implementation
uses GR32_PATHS, GR32_BRUSHES, GR32_VECTORUTILS, mmSystem, GR32_Polygons;

{$R *.dfm}

Procedure TForm1.InitArray;
var endL: Integer;
    i:    Integer;
begin
  SetLength(fpa, pbTest.Width * 2 - 20);
  endL:= High(fpa);
  for i := 1 to endL do begin
    fpa[i].X:= (i + 5) * 0.5;
    fpa[i].Y:= Round(pbTest.Height * (0.5 + 0.9 * (Random - 0.5)));
  end;
 end;

procedure TForm1.Panel1Click(Sender: TObject);
var tl: Int64;
  i: Integer;
begin
  //InitArray;
  tl:= TimeGetTime;
  for i := 0 to 24 do begin
    InitArray;
    pbTest.Repaint;
  end;
  panel1.Caption:= (IntToStr(Round((timeGetTime - tl)/25.0)));
end;

procedure TForm1.pbTestPaintBuffer;
var
  ida:            TArrayOfFloatPoint;
  FRenderer:      TPolygonRenderer32VPR;
  endl: Integer;
  can32:          TCanvas32;
begin
  pbTest.Buffer.Clear(clNavy32);
  if (Length(fpa) < 1) then Exit;
  FRenderer:= TPolyGonRenderer32VPR.Create(pbTest.Buffer);
  ida := GR32_VectorUtils.BuildPolyLine(fpa, 1.5, jsRound, esRound, 0.1);
  FRenderer.Color:= cLRed32;
  FRenderer.PolygonFS(ida);
  FRenderer.Free;
end;
end.
```
Started it, maximized it (1920 * 1024) and got approx 110ms for older version and 3.000ms for current version :-(
Tried also simple canvas32.polyline, there the result is 120ms (old version) vs. 900ms (new version).
In the Benchmark app both versions perform similar, but it does not use float coordinates, just integers.

**Comment by andersmelander** [comment] 2024-03-01 16:18
Please attach the project as a zip so I can use it to reproduce.

Btw, be aware that one of the breaking changes in Clipper2 that I mentioned is actually a _non-breaking_ breaking change in that the API stayed the same but the behavior changed. Specifically the interpretation of the Delta/Width parameter when offsetting (i.e. growing) polygons changed. Graphics32 attempt to hide this by adjusting the value passed to Clipper but I might have missed this adjustment in a place or two.
Anyway, as a consequence of this, if you are using an older version of Clipper2, then Graphics32's adjustment will become incorrect and you will get lines of half the expected width.

https://github.com/graphics32/graphics32/blob/772510c6cf988b661571f448302e3db053e1ca02/Source/GR32_Clipper2.pas#L156-L167

**Comment by ThomasNeumann** [comment] 2024-03-01 16:29
[2024-03-01-CanvasCurve.zip](https://github.com/graphics32/graphics32/files/14463507/2024-03-01-CanvasCurve.zip)

File attached

**Comment by andersmelander** [comment] 2024-03-01 17:45
Thanks. I have reproduced the problem with your example and holy hell, it's bad.

| Version | Commit | Time |
| ---- | ---- | ---- |
| Old (Graphics32 Grow) | 1 feb 2024: 1158e907517f5e1bc708a71359a8e6584a13129a | 16 mS |
| New (Clipper2 InflatePaths) | 7 feb 2024: dbef20a5959e9898d39b6a476e9c1c92aade13d5 | 457 mS | 

I noticed that the lines are visibly thicker in the new version. That could account for a tiny bit of the problem (more pixels drawn) but stepping through the code it's evident that the wast majority of time is spent inside Clipper.

**Old:**
![billede](https://github.com/graphics32/graphics32/assets/18141921/10973a8e-5b51-4b39-93ce-59ad2cdb7f6e)


**New:**
![billede](https://github.com/graphics32/graphics32/assets/18141921/6e076f6d-8d43-4a51-84e4-df1d504acbe7)

**Comment by andersmelander** [comment] 2024-03-01 18:18
If you change the `JoinStyle` to `jsMiter` it's much faster - but still a lot slower than the old version.

Until this can get resolved I suggest you undefine `USE_CLIPPER_GROW` in `GR32_VectorUtils.pas`.

**Comment by andersmelander** [comment] 2024-03-01 18:29
Actually, just use the latest version. I have now disabled Clipper2 Grow by default.

**Comment by AngusJohnson** [comment] 2024-03-06 12:38
I've been very tied up with other things so I'm somewhat late to the party here 😜. 
Anyhow I am very keen to investigate why Clipper2 is so much slower than Clipper1. 
But I need some sample code that uses the Clipper2 library that properly demonstrates this problem.
(I don't believe the Clipper library is being used in **`2024-03-01-CanvasCurve.zip`** sample code above.)

**Comment by andersmelander** [comment] 2024-03-06 13:14
> I don't believe the Clipper library is being used in 2024-03-01-CanvasCurve.zip sample code above

Yes it is - but not directly. The example calls `GR32_VectorUtils.BuildPolyline` -> `GR32_VectorUtils.BuildPolylineClipper` -> Clipper.InflatePaths.


>  I am very keen to investigate why Clipper2 is so much slower than Clipper1.

It's not Clipper1 vs Clipper2. It's Graphics32 `Grow` vs Clipper2 `InflatePaths`.

The old implementation of `GR32_VectorUtils.BuildPolyline` called `GR32_VectorUtils.Grow` but as you can see in the comments above, in commit dbef20a5959e9898d39b6a476e9c1c92aade13d5 Graphics32 switched from using its own Grow method:

https://github.com/graphics32/graphics32/blob/1158e907517f5e1bc708a71359a8e6584a13129a/Source/GR32_VectorUtils.pas#L1488-L1489

to using Clipper2's `InflatePaths`:

https://github.com/graphics32/graphics32/blob/772510c6cf988b661571f448302e3db053e1ca02/Source/GR32_VectorUtils.pas#L3153-L3166





The main reason for the dramatic slowdown (28 times slower!) appears to be the use of `JoinStyle=jsRounded`.
It's to be expected that rounded joins are expensive since they have more segments but the old implementation also used rounded joins and even when the join style is changed to mitered joins Clipper2 is still 7 times slower.

To be fair, the switch to Clipper2 _did_ solve a lot of minor annoying problems with the old implementation so it would be really sad if we had to revert (which I've already done - but hopefully only temporarily).

**Comment by AngusJohnson** [comment] 2024-03-06 13:37
> To be fair, the switch to Clipper2 did solve a lot of minor annoying problems

OK. I think I'm understanding the problem now. Clipper does use a `Union` operation to tidy up offsetting, and this does very significantly affect performance. However it should also produce a better render. (See discussion [here](https://github.com/AngusJohnson/Clipper2/issues/782#issuecomment-1965660857) for more info.)

**Comment by andersmelander** [comment] 2024-03-06 13:45
>  However it should also produce a better render.

Yes it does. But not 28 times better :-)

**Comment by AngusJohnson** [comment] 2024-03-06 20:46
> Yes it does. But not 28 times better :-)

I agree.

**Comment by andersmelander** [comment] 2024-03-06 21:59
> IOW, the polygon renderer will do the job that the Union operation does in Clipper2 (ie ignores the negative filled regions).

Well, I'm not really willing to let go of VPR (and the performance it brings) so that's not an option.

The reason I wanted to replace the old code with Clipper2 was mainly that we already used Clipper2 so it was silly to have that functionality duplicated and secondly that Clipper2 was actively maintained (contrary to the Grow function in Graphics32). 
But was really started me down this path was this old bug in Grow; A rounded rectangle made by inflating a rectangle (stroke:1px; corner:1px):

**Old Grow**
![billede](https://github.com/graphics32/graphics32/assets/18141921/a102ca6d-c9ed-43d9-8913-b444f0b2a91d)

**Clipper2**
![billede](https://github.com/graphics32/graphics32/assets/18141921/8420ff26-dba4-4066-8602-875a417ab567)


So my question now is really: Is there any hope that Clipper2 can be made able to better compete on performance in a case like this because I'd really like to use it by default. Twice as slow is okay for the many other benefits Clipper bring, but I can't justify a factor 7 slowdown.
I don't mind that rounded joins are slower, but it would be really nice if some of the logic that slows Clipper down could be short circuited when they aren't needed (if that is even possible. I obviously don't know the inner workings of Clipper). If I understood the discussion you linked to correctly, this is something that you are reluctant to pursue. Cost/benefit I guess.

**Comment by AngusJohnson** [comment] 2024-03-06 22:45
> So my question now is really: Is there any hope that Clipper2 can be made able to better compete on performance

No. But Clipper2's `Inflate` function really shouldn't be used when polygon rendering. Because Clipper2's `Inflate` is agnostic to an subsequent polygon rendering, it must use some code (ie a `Union` op) to remove unwanted negative areas. And as I said above, this internal `Union` op adds considerable overhead that isn't needed when performing polygon rendering. The renderer can/will also tidy up any negative areas. So I'm confident that the improvements you're seeing with Clipper2 (in rendering _quality_) aren't due to Clipper2's `Union` op, but to a better `Grow` function.

**Comment by andersmelander** [comment] 2024-03-06 22:52
> So I'm confident that the improvements you're seeing with Clipper2 (in rendering quality) aren't due to Clipper2's Union op, but to a better Grow function.

...and so how do I prevent Clipper from doing a union then? (I'm not giving up)
![precious](https://github.com/graphics32/graphics32/assets/18141921/d326dcb2-3902-4221-99f4-daac0c4ac33d)

**Comment by andersmelander** [comment] 2024-03-06 22:55
Ah... Can I just use `TClipperOffset` directly?

**Comment by AngusJohnson** [comment] 2024-03-06 23:14
> Ah... Can I just use TClipperOffset directly?

No, you can't. Sorry.
However, [this](https://github.com/AngusJohnson/Image32/blob/38ef4840436531c9e3782fa2dcf30618b363c48b/source/Img32.Vector.pas#L1855) `Grow` function should be very similar to Clipper2's `TClipperOffset.DoGroupOffset`. 
Nevertheless I'm pretty sure I've tweaked this functionality in Clipper2 more recently than `Img32.Vector.Grow`.

**Comment by andersmelander** [comment] 2024-03-06 23:22
> No, you can't. Sorry.

Hmm. Are you sure?

I can't see that `TClipperOffset` has any external dependencies. It appears to take a few simple parameters in the constructor and properties are simple too. Input polygons are added with `AddPath`/`AddPaths` and the result is returned by the `Execute` method.

What am I missing?

**Comment by AngusJohnson** [comment] 2024-03-07 04:04
> What am I missing?

https://github.com/graphics32/graphics32/blob/8dfb597327c34706433df8150590f0a54752eabe/Source/Clipper.Offset.pas#L710-L722

**Comment by andersmelander** [comment] 2024-03-11 14:02
I have now copied and shoehorned the `Grow` and `Outline` functions from @AngusJohnson 's Image32 library into Graphics32. The benchmark results in [the comment above](#issuecomment-1973622062)  have been updated with the new results.

The baseline values have changed a bit due to unrelated optimizations done elsewhere in Graphics32 since the original benchmark, but the result is that the new implementation appears to performs as well as the original. And this is with rounded joins, btw.

I will test it some more to make sure everything still works and then I just need to clean the code up a bit and find a good way to properly integrate it.

**Closed** 2024-03-12 00:51 UTC
Labels: bug

**Comment by AngusJohnson** [comment] 2024-03-12 02:00
Anders, I'm entirely happy for you to remove  just about all attribution to me (eg just one line attribution) and use the existing Graphics32 copyright too.

**Comment by ThomasNeumann** [comment] 2024-03-12 06:39
I'd like to say THANK YOU to both of you.

**Comment by andersmelander** [comment] 2024-03-12 11:08
> My test code for https://github.com/graphics32/graphics32/issues/283 doesn't work with the new Grow implementation (test function ThickLineByGrow doesn't draw anything, my old ThickLineSimple works fine): [RepaintTest.zip](https://github.com/graphics32/graphics32/files/14569502/RepaintTest.zip)

The original test case for #283 works for me ... but I can see that you have modified the project.

I see that you've used `Grow`. If you use `BuildPolyline` instead it works; `Grow`, with the parameters you have specified, is more for inflating a polygon and since you are passing it an empty polygon (less than three points is an empty polygon by definition) you get an empty result.

Regardless, I have rolled back the update. See #286.

**Comment by zedxxx** [comment] 2024-03-12 11:34
> `Grow`, with the parameters you have specified, is more for inflating a polygon and since you are passing it an empty polygon

If I define `USE_CLIPPER_GROW` or `USE_OLD_GROW` then Grow works as expected. But the new implementation with `USE_ANGUS_GROW` does not work.

**Comment by andersmelander** [comment] 2024-03-12 13:23
@AngusJohnson 

I've fixed the attribution so it matches the one in the other units. You are specified as the original developer of the code.

I'm slowly removing the "contributors" section from all the headers as it, for the most part, no longer really reflect who has actually contributed anything significant. It's all in the Git commit log anyway.

The unit is internal as it will only be referenced by the implementation section of GR32_VectorUtils. Therefore the unit and function names are internal too. I was pretty tired and in a rush when I named them so I just used your name :-) The short term plan is to keep the implementation in sync with "that other competing library". If and when I decide to refactor it beyond recognition, so it can no longer be synchronized, I might change the name. I guess the fate of the old implementation, which is still undecided, will also factor into this.
So, unless you object, I'd like to keep the names as they are now.

**Comment by AngusJohnson** [comment] 2024-03-12 19:07
> So, unless you object, I'd like to keep the names as they are now.

No objections 😁.

**Comment by AngusJohnson** [comment] 2024-03-15 03:39
> Nevertheless I'm pretty sure I've tweaked this functionality in Clipper2 more recently than `Img32.Vector.Grow`.
Anyhow, if `Img32.Vector.Grow` is better than `GR32_VectorUtils.Grow`, then you're welcome to copy whatever is useful

I've just had a closer look at `Img32.Vector.Grow` and its related functions and realise what a complete mess they are 😱.
I'm embarassed I pointed you to it. The Clipper2 grow function is very much cleaner (and I've given it a lot more attention too).

**Comment by andersmelander** [comment] 2024-03-15 04:01
Yeah it's a bit of a mess but I've heard you don't examine the rectum of a gift horse or something like that.

The old code was quite nice in terms of readability and simplicity but what good is that if it doesn't work? It might have been a simple fix but I would have had to invest a lot of time in getting to know the problem space before I could safely attempt a fix and I just don't have that time right now. So I opted for something that works, messy or not.

The Clipper2 solution would have been my preferred solution but, as you pointed out, it did too much and was too slow.

One thing I've been meaning to ask you: Do you see any reason to keep the two `Grow` variants, that take normals as a parameter, in the _public_ API? I mean, what purpose would that have?
https://github.com/graphics32/graphics32/blob/991db65428b4d7acd1e986617cce0b5d808a7808/Source/GR32_VectorUtils.pas#L202
https://github.com/graphics32/graphics32/blob/991db65428b4d7acd1e986617cce0b5d808a7808/Source/GR32_VectorUtils.pas#L205

**Comment by AngusJohnson** [comment] 2024-03-15 05:01
> Yeah it's a bit of a mess but I've heard you don't examine the rectum of a gift horse or something like that.

I've just now completed and uploaded a significant code tidy (and hoping I haven't broken anything significant 🤞.)

> Do you see any reason to keep the two Grow variants, that take normals as a parameter, in the public API?

No. They should really only be used within the VectorUtils unit. And I'm not sure the FixedPoint Grow function is needed given that ?? all line and polygon rendering is now done using floating points in Graphics32.

**Comment by andersmelander** [comment] 2024-03-15 11:07
> I've just now completed and uploaded a significant code tidy (and hoping I haven't broken anything significant 🤞). It still needs further tidying but it's almost intelligible now.

I've just integrated it. Nicely done, but yes, there's a few unused vars to clean up. Also, rounded ends aren't working; `spr` (which is used in `DoRound`) isn't calculated unless `joinStyle=jsRound`.

>  I'm not sure the FixedPoint Grow function is needed given that ?? all line and polygon rendering is now done using floating points in Graphics32.

Yes, it's all floats now with the default setup but since I have made the setup pluggable that can change. For example if Clipper is being used as the grow-backend then it's fixed. Also, I can't really break the public API by removing the fixed functions.
Regardless, I've now moved the "normals" methods to the protected section.

> Also, VectorUtils.Grow isn't like Clipper2.Inflate (in that the negative area regions still need cleaning up), so it needs to be used judiciously (eg in drawing functions with EvenOdd fill). So if it's exposed for general use, it's likely confuse library users (even when carefully documented).

Well that might be a problem, but then it is also a problem for `BuildPolyline` and `BuildPolyPolyLine` since they suffer from the same problem (being thin wrappers that call `Outline` which in turn calls `Grow`). The old implementation also didn't remove negative areas so at least it's not a regression.
As far as I can see your own library will have the same problem as I guess `Outline` is your API to "inflate" a polyline/polygon, right?

**Outline/Grow**
![billede](https://github.com/graphics32/graphics32/assets/18141921/0e04c171-17a2-48a5-9d79-647ad50f2271)

**Clipper2**
![billede](https://github.com/graphics32/graphics32/assets/18141921/ae79b6a9-08c3-4504-9bb8-20555b60107e)

**Comment by AngusJohnson** [comment] 2024-03-15 11:55
> eg in drawing functions with EvenOdd fill

Oops, NonZero fill.

**Comment by andersmelander** [comment] 2024-03-15 12:55
> I'd have to check, but iirc I think I've adopted a few mistakes from Graphics32, and Outline should either be renamed or not exposed, and Inflate be used for outlining.

Now I'm confused.
Did you mean `InflatePaths` in Clipper? Because there's no `Inflate` in Image32 and I can't see that there's another API for offsetting a polyline/polygon.

**Comment by AngusJohnson** [comment] 2024-03-15 15:59
> Did you mean InflatePaths in Clipper

Yes.

**Comment by AngusJohnson** [comment] 2024-03-15 22:19
> As far as I can see your own library will have the same problem as I guess Outline is your API to "inflate" a polyline/polygon, right?

Right. But that's now fixed too 😁.

**Comment by andersmelander** [comment] 2024-03-16 00:33
I have integrated the latest changes. 

- I removed an unused var in `RoughOutline`.
- The rounded joins and line ends were pretty choppy so I replaced the calculation in `CalcRoundingSteps` with the algorithm used in the `Arc` function. I could probably just have doubled the calculated steps for the same effect.

| Before | After |
| ----- | ----- |
| ![billede](https://github.com/graphics32/graphics32/assets/18141921/d1fc519c-fb5d-4b69-beb0-4a8f31535d48) | ![billede](https://github.com/graphics32/graphics32/assets/18141921/45ab6b48-77f3-437d-9fa1-038444a7c49f) |

**Comment by andersmelander** [comment] 2024-03-16 23:47
FWIW, I've found and fixed the cause of this:

> what really started me down this path was this old bug in Grow; A rounded rectangle made by inflating a rectangle (stroke:1px; corner:1px):
> 
> ![billede](https://private-user-images.githubusercontent.com/18141921/310667258-a102ca6d-c9ed-43d9-8913-b444f0b2a91d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDY5MTEsIm5iZiI6MTcxMDUwNjYxMSwicGF0aCI6Ii8xODE0MTkyMS8zMTA2NjcyNTgtYTEwMmNhNmQtYzllZC00M2Q5LTg5MTMtYjQ0NGYwYjJhOTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEyNDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYzM5ZmQ3M2I1Y2I1MzczOThhMDQwZTcyNzQyMTQ2MmRkMWM2NjYzZjE5MTBiOWI5NmZjYzZlMTdiOWNjZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1vUlN7KUMe3hYu1oCS05jjRYDo_iN5P679FhfXjUynU)

The rounded corner was missing the last point of the arc. The fix was three lines of code :-/
