### ISSUE TITLE
TBitmap32.Textout with LCL-Gtk backend does't print anything

### ISSUE THREAD

**Issue by artelogic-com** [graphics32/graphics32#187] opened 2022-05-22 12:56 UTC
Even the simplest (TBitmap32.)Textout(0,0,'ABCDE') brings out nothing.

**Comment by andersmelander** [comment] 2022-05-22 20:53
Have you tried one of the other `Textout` methods?

I can see that the `Textout(X, Y: Integer; const Text: string)` method is implemented differently in the LCL-Gtk backend than the two other overloads.

**Comment by artelogic-com** [comment] 2022-05-23 08:56
Now I did. But none of them shows any text.

**Comment by andersmelander** [comment] 2022-05-24 21:25
As I have neither FPC nor Linux installed there's not much _I_ can do about this so the best we can hope for is that someone else will have a go at it.

Btw, I assume you have tried some of the examples that demonstrate text output (e.g. the RenderText project)?

**Comment by artelogic-com** [comment] 2022-05-24 21:29
No, I didn't try any examples. I just use my own controls I developed 10 years ago with Delphi and Graphics32. 

But I can do it...

**Comment by andersmelander** [comment] 2022-05-24 21:35
Yes, please do. Just to make sure that we're dealing with a bug and not something else (e.g. you've forgotten to set the font color or something like that ;-) ).

FWIW, here's one way to use it:

    Buffer.Font.Size := 10;
    Buffer.Font.Color := clRed32;
    Buffer.Textout(Buffer.BoundsRect, DT_SINGLELINE or DT_CENTER or DT_VCENTER or DT_NOPREFIX, 'Hello world');

**Comment by artelogic-com** [comment] 2022-05-24 21:44
Just a black TImage32 with RenderText project. Is the media.rc relevant, because I have to comment it out?

**Comment by andersmelander** [comment] 2022-05-24 21:47
Bummer :-(
The `media.rc` file just contains the application icon. I don't know why it was included that way.

**Comment by artelogic-com** [comment] 2022-05-24 22:37
procedure TLCLBackend.Textout(X, Y: Integer; const Text: string);
begin
  UpdateFont;

  if not FOwner.MeasuringMode then
    Canvas.TextOut(X, Y, Text);
end;

AFAIUnderstand, this can never work. Text is given to Canvas of FBitmap (which is TBitmap, probably used as a helper in the backend). But that's it. How can one expect to see any changes on the Bitmap32 the Backend belongs to? ;)

**Comment by andersmelander** [comment] 2022-05-24 23:15
I believe `FBitmap` is used as the internal bitmap storage. On Windows a DIB section is used but it could just as well have been a `TBitmap` with pf32bit PixelFormat.

As far as I can see here's what happens:

- `Canvas.TextOut` causes `CanvasChangedHandler` to be called.
- `CanvasChangedHandler` calls `CanvasChanged`.
- `CanvasChanged` fires the `OnCanvasChange` event.
- `OnCanvasChange` is handled by `TBitmap32.CanvasChanged`.
- `TBitmap32.CanvasChanged` calls `TBitmap32.Changed`.

from here on I don't know what happens but I'm guessing that `TBitmap32.Changed` will end up notifying the owner (e.g. `TImgView32`) that it needs to be drawn.
It looks as if it _should_ work but obviously something goes wrong along the way.

**Comment by artelogic-com** [comment] 2022-05-25 06:10
TCustomBitmap32.Changed calls FOnAreaChanged, if Assigned. But it is not Assigned.

Btw, I am using a TPaintBox32 on a TForm. And in the PaintBuffer-Event I do:
  with pb1.Buffer do begin
    FillRect(0,0,Width-1,Height-1,$FFFFFF00); // which actually paints the box in AQUA
    pb1.Buffer.Font:=Self.Font;
    pb1.Buffer.Font.Size:=10;
    pb1.Buffer.Font.Color:=clBlack;
    pb1.Buffer.Textout(0,0,'ABCDE');
  end;

**Comment by andersmelander** [comment] 2022-05-25 14:08
> TCustomBitmap32.Changed calls FOnAreaChanged, if Assigned. But it is not Assigned.

If you are using a `TPaintBox32` then it doesn't need to be assigned because the bitmap will be drawn to screen (by `TCustomPaintBox32.Paint`) once your `OnPaintBuffer` handler returns. In theory all you need to do is draw whatever you need on the buffer and the control should take care of the rest.

In your example, if you can see that the `FillRect` does something which means that `TPaintBox32` does draw the buffer. So we know that that part works. I guess we're back to that there's something wrong with `Textout`.

Are you are to step through the code in a debugger? It would be interesting to see if `Textout` produces the call chain I mentioned above.

> FillRect(0,0,Width-1,Height-1,$FFFFFF00); // which actually paints the box in AQUA

I'm guessing you're on a big-endian system because on little-endian systems (such as Windows) $FFFFFF00=yellow and $FF00FFFF=aqua. Are you running on an old version of Linux?

**Comment by artelogic-com** [comment] 2022-05-25 17:28
Yes, it produces the chain, but ends up in TCustomBitmap32.Changed which would call FOnAreaChanged, if it was assigned. But it isn't, because RepaintMode is rmFull. But the other RepaintModes, which produce an assigned FOnAreaChanged, do not bring out any text, either.

And no, I am not on big-endian. It's an intel i9 running a quite up-to-date Kubuntu. But I encounter strange color behaviour of TImage32 right now, when I wanted to check the color value. Have to investigate deeper, but no time now...

**Comment by andersmelander** [comment] 2022-05-25 21:17
> And no, I am not on big-endian. It's an intel i9 running a quite up-to-date Kubuntu. But I encounter strange color behaviour of TImage32 right now, when I wanted to check the color value.

Okay, I see the problem here. Graphics32 assumes that FPC on Linux is big endian. From GR32_Compiler.inc :
```
{$IFDEF COMPILERFPC}
...
  {$IFNDEF WINDOWS}
    {$DEFINE RGBA_FORMAT}
  {$ENDIF}
...
{$ENDIF}
```
While that was probably valid when it was written a better solution today (FPC 1.05 and later) might be:
```
{$IFDEF COMPILERFPC}
...
  {$IFDEF ENDIAN_BIG}
    {$DEFINE RGBA_FORMAT}
  {$ENDIF}
...
{$ENDIF}
```
**However...** It seems that regardless of endianness or platform FPC always uses the BGRA format while Delphi uses the RGBA format. https://wiki.lazarus.freepascal.org/Developing_with_Graphics#TColor
This means that the correct method is probably:
```
{$IFDEF COMPILERFPC}
...
  {$DEFINE RGBA_FORMAT}
...
{$ENDIF}
```
which for you (FPC on Linux, x86) gives the same result as the original :-(


> Yes, it produces the chain, but ends up in TCustomBitmap32.Changed which would call FOnAreaChanged, if it was assigned. But it isn't, because RepaintMode is rmFull.

You're missing the point. Since your `FillRect` produces output we know that the paintbox is drawing the buffer onto the display thus we know that the notification chain isn't the problem.
The problem is that `Textout` for some reason simply isn't drawing onto the internal backend buffer.

When you get time would you mind trying this simple change:

**GR32_Backends_LCL_Gtk** in the method `TLCLBackend.InitializeSurface`:
Replace:
```
  { We allocate our own memory for the image }
  FRawImage.Description.Init_BPP32_B8G8R8A8_BIO_TTB(NewWidth, NewHeight);
```
with:
```
  { We allocate our own memory for the image }
  FRawImage.Init; // <- Just add this line
  FRawImage.Description.Init_BPP32_B8G8R8A8_BIO_TTB(NewWidth, NewHeight);
```

**Comment by artelogic-com** [comment] 2022-05-26 07:27
No success with this.

**Comment by artelogic-com** [comment] 2022-05-26 08:08
> You're missing the point. Since your FillRect produces output we know that the paintbox is drawing the buffer onto the display thus we know that the notification chain isn't the problem.
The problem is that Textout for some reason simply isn't drawing onto the internal backend buffer.

For me it looks like TextOut draws text on the canvas, but the canvas is never drawn to the internal buffer. (And I thought, we would expect an OnChangedSomething-event handler to do so)

**Comment by andersmelander** [comment] 2022-05-26 11:46
The canvas _is_ the internal buffer. `TCanvas` is just an abstraction on top of a bitmap, a printer, the screen etc.

**Comment by andersmelander** [comment] 2022-05-26 21:29
Well it's an "interesting" result but it's not surprising given the changes you've made :-)

As I understand it the backend contains two bitmap objects: One provides the bitmap memory storage and the other provides pointer access to this memory. The first one can only be modified through the high level TCanvas methods (Textout, Ellipse) and the other one is used by Graphics32's optimized methods (FillRect, Line). This design is driven by the fact that FPC's TBitmap has no ScanLine property or similar pixel memory access mechanism.

I think what you've done is more or less remove the connection between the two bitmaps which is why they're not showing the same.

The problem is probably that changes (e.g. Textout) made to the internal TBitmap isn't propagated to the other bitmap. Maybe the design of the backend is flawed and what it's trying to do simply isn't possible. I'll have to investigate this some more.

**Comment by artelogic-com** [comment] 2022-05-27 07:44
No, the backend has only one bitmap. As before. I just removed the more complicated way it was created. But it seems it has always two buffers, one you can access directly (RawImage.Data) and one over Canvas. And they are not synchronized as we wish. But there is little synch, the background-color is the same. So FillRect has worked. And Line would also work, if it was called before TextOut and Ellipse. So all you do by DirectAccess before any Canvas-Operation is reflected in the result.

Look here:
[Screenshot_20220527_094155.zip](https://github.com/graphics32/graphics32/files/8784846/Screenshot_20220527_094155.zip)
Done by:
procedure TForm1.pb1PaintBuffer(Sender: TObject);
begin
  pb1.Buffer.FillRect(0,0,pb1.Buffer.Width,pb1.Buffer.Height,TColor32($FFFFFF00));
  pb1.Buffer.Line(0,pb1.Buffer.Height,pb1.Buffer.Width,0,TColor32($FF88AACC),False);
  pb1.Buffer.Font:=Self.Font;
  pb1.Buffer.Font.Size:=10;
  pb1.Buffer.Font.Color:=clBlack;
  pb1.Buffer.Textout(0,0,'ABCDE');
  pb1.Buffer.Canvas.Ellipse(10,10,50,100);
  pb1.Buffer.Line(0,0,pb1.Buffer.Width,pb1.Buffer.Height,TColor32($FF88AACC),False);
end;

procedure TForm1.FormDblClick(Sender: TObject);
begin
  Image1.Picture.Assign(TLCLBackend(pb1.Buffer.Backend).Bitmap);
  Image32_1.Bitmap.Assign(TLCLBackend(pb1.Buffer.Backend).Bitmap);
end;

Also color-management is interesting. ;)

**Comment by artelogic-com** [comment] 2022-05-27 22:24
I am afraid, it is not possible to get canvas-functionality and a fixed pointer to pixel data with GTK. :(

**Comment by andersmelander** [comment] 2022-05-27 22:45
> I am afraid, it is not possible to get canvas-functionality and a fixed pointer to pixel data with GTK. :(

I had also just about come to that conclusion but then I realized that since [BGRABitmap](https://wiki.freepascal.org/BGRABitmap) apparently manages it then it should be possible for Graphics32 too.

I'm currently reading though the BGRABitmap source. The relevant source unit seems to be `BGRALCLBitmap.pas`. It seems to be doing much of the same as the Graphics32 backend.
In my opinion the backend is a bit of a mess. The `TBGRALCLBitmap` code appears to be much easier to understand so maybe a complete rewrite of the backend would be best.

**Comment by artelogic-com** [comment] 2022-05-27 22:50
But they do the TextOut different. They text out on a second bitmap and then draw this bitmap on their BGRABitmap. So no use of canvas directly with the BGRABitmap. If I understood it correctly.
Of course this is a way. Maybe the only one.

**Comment by artelogic-com** [comment] 2022-05-27 22:53
But probably canvas would not be important, if there was GR32_Text_LCL_Gtk.pas ;)

**Comment by artelogic-com** [comment] 2022-05-27 22:59
Actually my controls use the old GR32_Text.pas by Angus Johnson. I am pretty sure, you remember those days.

**Comment by artelogic-com** [comment] 2022-06-01 15:20
Do you think, there is any hope?

**Comment by artelogic-com** [comment] 2022-06-04 20:09
Ok, I made some changes to the backend. With this I get Text and even RenderText. But still no Lines or Ellipses and so on by Canvas, but I think since GR32 offers those directly, they are not really necessary.

In GR32.pas I had to add 2 lines. Search for "//cag". I am sure, they could be conditional.

[GR32_Backends_LCL_Gtk.zip](https://github.com/graphics32/graphics32/files/8838624/GR32_Backends_LCL_Gtk.zip)
,

**Comment by artelogic-com** [comment] 2022-06-04 20:21
Ups, sorry forgotten:

In Gr32 line 1337 I put in:
{$IFDEF FPC} {$IFDEF LINUX}
{$DEFINE SWAP_RB}
{$ENDIF}{$ENDIF}
{$IFDEF SWAP_RB}
Result := $FF000000 or (WinColor and $FFFFFF);
{$ELSE}
Result := $FF shl 24 + (WinColor and $FF0000) shr 16 + (WinColor and $FF00) +
  (WinColor and $FF) shl 16;
{$ENDIF}

which corrects my background color problem, but now (with this) the font color is swapped.

**Comment by artelogic-com** [comment] 2022-06-05 14:34
I added/changes this in GR32.pas also, which corrects the font color:

procedure TextBlueToAlpha(const B: TCustomBitmap32; Color: TColor32);
(*
asm
    PUSH    EDI
    MOV     ECX, [B+$44].Integer
    IMUL    ECX, [B+$40].Integer
    MOV     EDI, [B+$54].Integer
    @PixelLoop:
    MOV     EAX, [EDI]
    SHL     EAX, 24
    ADD     EAX, Color
    MOV     [EDI], EAX
    ADD     EDI, 4
    LOOP    @PixelLoop
    POP     EDI
end;
*)
var
  I: Integer;
  P: PColor32;
begin
  // convert blue channel to alpha and fill the color
  Color := Color and $00FFFFFF;
  P := @B.Bits[0];
{$IFDEF SWAP_RB}
  for I := 0 to B.Width * B.Height - 1 do begin
    if P^ <> 0 then
      P^ := ((P^ and $FF0000) shl 8) or ((Color and $FF) shl 16) or ((Color and $FF0000) shr 16) or (Color and $FF00);
    Inc(P);
  end;
//  B.SwapRB;
{$ELSE}
  for I := 0 to B.Width * B.Height - 1 do
  begin
    if P^ <> 0 then
      P^ := ((P^ and $FF) shl 24) or Color
    else
      P^ := 0;  // cag why set to 0? it is only executed if it is already 0
    Inc(P);
  end;
{$ENDIF}
end;

procedure TextScaleDown(const B, B2: TCustomBitmap32; const N: Integer;
  const Color: TColor32); // use only the blue channel
var
  I, J, X, Y, P, Q, Sz, S: Integer;
  Src: PColor32;
  Dst: PColor32;
begin
  Sz := 1 shl N - 1;
  Dst := PColor32(B.ScanLine[0]);
  for J := 0 to B.Height - 1 do
  begin
    Y := J shl N;
    for I := 0 to B.Width - 1 do
    begin
      X := I shl N;
      S := 0;
      for Q := Y to Y + Sz do
      begin
        Src := B2.PixelPtr[X, Q];
        for P := X to X + Sz do
        begin
          {$IFDEF SWAP_RB}
          S := S + (Integer(Src^ and $00FF0000) shr 16);
          {$ELSE}
          S := S + Integer(Src^ and $000000FF);
          {$ENDIF}
          Inc(Src);
        end;
      end;
      S := S shr N shr N;
      {$IFDEF SWAP_RB}
      Dst^ := TColor32(S shl 24) or ((Color and $FF) shl 16) or ((Color and $FF0000) shr 16) or (Color and $FF00);
      {$ELSE}
      Dst^ := TColor32(S shl 24) + Color;
      {$ENDIF}
      Inc(Dst);
    end;
  end;
end;


But I am pretty sure, that there must be an error somewhere else or a better overall solution.

**Comment by andersmelander** [comment] 2022-06-05 21:36
If you want these changes to be applied to the source then you really should create a pull request instead. It's not feasible for me to update the source based on the different changes you post here.

>     {$IFDEF FPC} {$IFDEF LINUX}
>     {$DEFINE SWAP_RB}
>     {$ENDIF}{$ENDIF}

This corresponds to the old definition of the `RGBA_FORMAT` define. I thought we had determined that FPC used RGBA format on all platforms - Not only on Linux. Was that then incorrect?
https://github.com/graphics32/graphics32/issues/187#issuecomment-1137856471

> I added/changes this in GR32.pas also, which corrects the font color:
>     procedure TextBlueToAlpha(const B: TCustomBitmap32; Color: TColor32);

I think this reveals the cause of at least some of the color problems. If things worked like they should have then it shouldn't be necessary to swap R and B when assigning a TColor32 to a pixel since the RGB layout of TColor32 should match the RGB layout of the pixels (by the way make sure you aren't using the clXXX32 color constants since those are assume BGRA format).

The problem _could_ be that the backend is using a bitmap of an incorrect format. From what I can see it's using BGRA format while it probably should be using RGBA since `RGBA_FORMAT` is defined.
Try changing this in the backend in `TLCLBackend.InitializeSurface`:

```
{$ifdef RGBA_FORMAT}
  FRawImage.Description.Init_BPP32_R8G8B8A8_BIO_TTB(NewWidth, NewHeight);
{$else RGBA_FORMAT}
  FRawImage.Description.Init_BPP32_B8G8R8A8_BIO_TTB(NewWidth, NewHeight);
{$endif RGBA_FORMAT}
```

With regard to `TextBlueToAlpha` and `TextScaleDown`: You don't need to change the handling of the blue channel since they are not dependent on the actual channel. They work the same on the other channels. They are supposed to operate on white text so R=G=B.

**Comment by artelogic-com** [comment] 2022-06-06 07:21
> Try changing this in the backend in TLCLBackend.InitializeSurface

I had changed the backend already. Actually was that my most important post here. ;)

**Comment by artelogic-com** [comment] 2022-06-06 07:25
The color regarding code I posted here was just to show/discuss that the color problem isn't solved completely. And, of course, not to be applied to the repository. But it was surely the wrong place here in this issue.

**Comment by andersmelander** [comment] 2022-07-01 16:39
@x2nie, as you've discovered your changes are now in the LCL_GTK_Backend branch. Since you've closed the PR I will continue the discussion here.

It seems to me that the solution you've implemented almost duplicates the existing solution. The difference is that yours' works :-) As far as I can tell the reason the existing one doesn't work is that it was never completed.

Here's my understanding of how the **existing** backend was _supposed_ to work:

- The backend contains two independent "buffers":
  - `FBitmap` (TBitmap): Used for stuff that needs a TCanvas.
  - `FRawImage` (TRawImage): A raw buffer/pixmap which is used for the stuff that needs direct pixel access (i.e. most of Graphics32).
- When the canvas is modified, the changes needs to be copied back to the raw buffer (this is missing).
- When the raw buffer is modified, the changes needs to be copied to the canvas (also missing).

As far as I can tell your changes adds an additional pixmap which in effect replaces the TRawImage since you "highjack" the pixel pointer (`FBits`).
Additionally you handle the missing copying back and forth between your pixmap and the canvas in a few situations. This is good because it has made clear that the primary reason the existing code didn't works was that this part was missing. However what isn't so good is that your solution doesn't handle all the other situations where the bitmap is modified via the canvas. So we're close, but no cigar - yet.

The solution I had envisioned to solve the performance problem was that we used two flags to indicate if the canvas and/or the pixmap had been modified. If we needed the canvas, and the pixmap had been modified, then we copied the pixmap to the canvas. If the pixmap was needed, and the canvas had been modified, then we copied the canvas to the pixmap. This would prevent unnecessary copy between the two buffers; The copy would only happen when it was absolutely necessary.
However in order for the above to work:

1. We would need to get notified when the canvas is modified.
This is easy since that notification mechanism is already in place.

2. We would need to get notified when the pixmap is modified.
Unfortunately there isn't any way to achieve this reliably. First of all the backend doesn't get notified if the pixmap is modified (e.g. via TBitmap32.Changed) and even if it did there would be nothing preventing an outer layer keeping a direct pointer reference to the pixmap data with the assumption that the pixmap was up to date at all times (as it is on Windows/Delphi).

Okay, so _that_ performance improvement is out of the question but what about getting the backend to support arbitrary operations on the canvas (which is what your solution lacks)? Well, what we need is:

1. The canvas must be up to date (i.e. contain a copy of the pixmap data) when we operate on it
2. If the canvas is modified then we need to update the pixmap with the content of the canvas.

This is actually pretty easy to achieve within the existing framework (simplified):

1. In the Canvas property getter we copy the pixmap to the canvas:
```
function TLCLBackend.GetCanvas: TCanvas;
begin
  CopyPixmapToCanvas;
  Result := FBitmap.Canvas;
end;
```
2. When the canvas is modified we copy the canvas to the pixmap:
```
procedure TLCLBackend.CanvasChanged;
begin
  CopyCanvasToPixmap;
  if Assigned(FOnCanvasChange) then
    FOnCanvasChange(Self);
end;
```

This basically does the same as your solution. And we can even sneak in a few performance optimizations if we make some assumptions. We only need to update the canvas if the pixmap has been accessed and if we assume that this is always done through the backend `Bits` property, via the `GetBits` method, then we can set a flag in `GetBits` indicating that the canvas needs to be updated. Similarly we can defer copying the canvas to the pixmap until `GetBits` is called.

Finally I'd like your thoughts on keeping the existing `TRawImage` solution (with all the above changes) in preference to using `PGdkPixbuf` as you've done. What are the pros and cons of one over the other?

**Comment by andersmelander** [comment] 2022-07-03 14:16
I've committed my proposed solution. Since I don't have FPC installed it's completely untested and will probably need to be adjusted.

**Comment by x2nie** [comment] 2022-07-04 15:36
Yeah..! it looks great at first sight. I am in completing several missing method required by class-interface.
I might create another PR for these methods.

**Comment by x2nie** [comment] 2022-07-04 23:48
1. I think the `bitmap32.Textout()` works as expected, but the Bits isn't yet updated in the time it is needed.
in other words, procedure `TextBlueToAlpha` is working with old Bits. 
![image](https://user-images.githubusercontent.com/1678529/177225808-206ae69d-2f3f-4a04-af90-8f8de3bfb393.png)

**Comment by andersmelander** [comment] 2022-07-05 09:01
I think we should focus on the TextOut problem here. Otherwise the discussion gets too confusing and the choice of RGBA or BGRA is not the cause of the problem. I think we agree on this.

As far as I can tell, from looking at the source, BGRABitmap is doing the same thing as us: Copying data back and forth between the canvas and an internal pixmap. I even believe the LCL TBitmap is doing this internally too. That is why TBitmap.RawImage.Data is only valid between a BeginUpdate/EndUpdate pair.
The reason this separation between between canvas and pixmap exists at all is that the two could be located in different processes or even on different physical machines ([X server/X terminal](https://en.wikipedia.org/wiki/X_Window_System)). I believe the version of GTK used (version 2) requires this separation. Newer versions of GTK does not but that should be handled by the other LCL backends.

Anyway I will see if I can get Lazarus installed on Windows so I can reproduce the problem. It seems that the assumption I've made in `CopyCanvasToPixmap`, that the canvas pixels can be copied from `FBitmap.RawImage.Data` to our pixmap, doesn't hold.

**Comment by x2nie** [comment] 2022-07-05 10:59
okay. lets focus on `TextOut` here. :)

**Comment by andersmelander** [comment] 2022-07-05 11:24
> I will see if I can get Lazarus installed on Windows so I can reproduce the problem.

No luck so far...

I have successfully installed Lazarus, installed the GR32 package and compiled and run the RenderText example (using the LCL_Win backend). So far so good.

In order to test the GTK backend I have:
1. Installed the GTK-2 runtime from https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer
2. Added the LCLWidgetType:=gtk2 macro to the RenderText project and rebuilt.
3. Copied RenderText.exe into the GTK .\bin folder (to avoid having GTK in the system path) and run it.

But I get a run time error:
> The procedure entry point gtk_file_selection_get_selections could not be located in the dynamic link library libgtk-win32-2.0-0.dll. 

From the GTK documentation I can see that [`gtk_file_selection_get_selections` is deprecated in GTK-2](https://developer.gimp.org/api/2.0/gtk/GtkFileSelection.html#gtk-file-selection-get-selections) so I thought that maybe I should target GTK-1 instead however that gives me compiler error in the LCL:
> X is required for GTK1

I'll now try to get it working with an older version of GTK-2 instead.

**Comment by x2nie** [comment] 2022-07-05 13:41
okay. 
Here what I found:

first time the rendertext demo run,
1. TLCLBackend.CanvasChanged hit first. 
Caused by `procedure TCanvas.TextOut(X,Y: Integer; const Text: String);` //canvas.inc#1363
caused by `procedure TLCLBackend.Textout(X, Y: Integer; const Text: string);`
2. TLCLBackend.CopyCanvasToPixmap the second breakpoint visited.
and the form is then visible.

**Comment by x2nie** [comment] 2022-07-05 13:51
now, I click the button with caption of ` -1 `:
1. TLCLBackend.NeedCanvas ( hit 7 times )
2. TLCLBackend.CanvasChanged
3. TLCLBackend.CopyCanvasToPixmap

**Comment by andersmelander** [comment] 2022-07-05 15:06
That sequence of event is as expected so at least we know that the basic canvas <-> pixmap algorithm works. Now we just need to determine why the canvas isn't being copied to the pixmap in `CopyCanvasToPixmap`.

In case the problem is that `FBitmap.RawImage.Data` doesn't actually contain the canvas pixels data as I've assumed, is there some other way we can the pixel data transferred from the canvas to the pixmap?
I would have rather used the higher level functions of the LCL but if that doesn't work I guess we could use `gdk_pixbuf_get_from_drawable` like you originally did. Something like this:

```
procedure TLCLBackend.CopyCanvasToPixmap;
var
  PixBuf: PGdkPixbuf;
  P: TPoint;
  SourceBits: pointer;
begin
  // Allocate a new pixbuf, 8 bits per channel with alpha.
  PixBuf := gdk_pixbuf_new(GDK_COLORSPACE_RGB, True, 8, FWidth, FHeight);
  try

    P := TGtkDeviceContext(Canvas.Handle).Offset;

    // Fill the pixbuf with the canvas pixel data
    if (gdk_pixbuf_get_from_drawable(PixBuf, 
      TGtkDeviceContext(Canvas.Handle).Drawable, nil, 
      P.X,P.Y, 0,0, FWidth, FHeight) = nil) then
      raise Exception.Create('[TLCLBackend.CopyCanvasToPixmap] gdk_pixbuf_get_from_drawable failed');

    // Get a pointer to the pixbuf pixel data
    SourceBits := gdk_pixbuf_get_pixels(PixBuf);

    // Copy data from pixbuf to pixmap
    MoveLongword(SourceBits^, FBits^, FWidth*FHeight);

  finally
    g_object_unref(PixBuf);
  end;

  FPixmapDirty := False;
  FCanvasDirty := False;
end;
```

**Comment by x2nie** [comment] 2022-07-05 16:23
> is there some other way we can the pixel data transferred from the canvas to the pixmap?
Yes, using `TBitmap.Canvas.Pixel[ x, y ]` . but internally it seem as big function with  long lines ( I couldn't understand)

**Comment by andersmelander** [comment] 2022-07-05 16:37
Excellent!

> Maybe we can reduce the area being copied by detecting the "text size" /textExtend ?

Yes, sure. That should be possible. The simple solution would be to calculate the union rect of all areas changed between `CopyPixmapToCanvas` and `CopyCanvasToPixmap`.
In order to get optimized updates working on the client side we also need to add the missing handling of `MeasuringMode`. See the other backends.

> or by detecting the current canvas position compared between before & after textout (changing & changed event of TCanvas) ?

The canvas position should always be (0,0), unless I'm mistaken, since the canvas just represents the host side (i.e. X Server) copy of the bitmap. Or did you mean the current "pixel cursor" position? In case such a thing exists then that is not reliable as the position would depend on how the text was rendered on the server.

> Yes, using TBitmap.Canvas.Pixel[ x, y ] . but internally it seem as bigger function with long lines ( I couldn't understand)

LOL. That would definitely be a lot slower. It appears to be creating a virtual 1x1 bitmap representation of a pixel on the canvas and then read a pixel from this bitmap. Also I don't think it supports alpha.

**Comment by x2nie** [comment] 2022-07-06 02:07
Okay.. I need to cleanup some local tests first.

**Comment by x2nie** [comment] 2022-07-06 04:49
![image](https://user-images.githubusercontent.com/1678529/177471057-11e7331f-edc9-4fb5-82c7-70e1a0860dcd.png)

**Closed** 2022-07-06 07:58 UTC
Labels: bug
