### ISSUE TITLE
GR32_Image.pas : ScrollToCenter(X,Y : Integer) is not working properly

### ISSUE THREAD

**Issue by chulwoongjeon-stemcell** [graphics32/graphics32#35] opened 2018-01-30 00:32 UTC
If the image was zoom-in if the image moves to the other area, then the new area is not updated properly.

**Comment by CWBudde** [comment] 2019-01-04 02:30
Thanks for reporting. However, to increase the chance to get this fixed, it would be nice if you could supply some code to expose this issue

**Comment by lamdalili** [comment] 2019-05-29 10:14
this happens when you are not drawing directly on the bitmap, the use of a new event like OnScaleShiftChange is needed...
proposed code:
[code]
  TGLayer=class(TBitmapLayer)
   ...
  end;
 procedure TGLayer.Changed;
 begin
     _Changed:=True;
      inherited;
 end;
procedure TGLayer.Paint(Buffer: TBitmap32);
begin
   if _Changed then
   begin
     DrawPolys; // Draw bitmap for new size
       _Changed:=False;
   end;
procedure TGLayer. DrawPolys;
var
  H,W:integer;
  t:TArrayOfArrayOfFloatPoint;
  ScaleX, ScaleY: TFloat;
  B:TFloatRect;
begin
  if Group then
     Exit;
  LayerCollection.GetViewportScale(ScaleX, ScaleY);
  with GetAdjustedRect(Location) do
  begin
    t:=GR32_VectorUtils.ScalePolyPolygon(Src,ScaleX, ScaleY);
    W:=Ceil(Abs(Right-Left));
    H:=Ceil(Abs(Bottom-Top));
    Bitmap.DrawMode:=dmBlend;
    Bitmap.BeginUpdate;
    Bitmap.SetSize(W,H);
    Bitmap.Clear(0); 
    PolyPolylineFS(Bitmap,t,clBlack32,False);
    Bitmap.EndUpdate;
  end;
end;
end;
 
and add this code to  TImgView32.DoScaleChange

procedure TImgView32.DoScaleChange;
var
 I:integer;
begin
  inherited;
  Buffer.BeginUpdate;
  for I := 0 to Layers.Count - 1 do
     Layers.Items[I].Changed();
  Buffer.EndUpdate();
end;

[/code]

**Comment by lamdalili** [comment] 2019-05-29 10:38
unit Unit1;
this happens when you are not drawing directly on the bitmap, the use of a new event like OnScaleShiftChange is needed...
proposed code:
[code]
TGLayer=class(TBitmapLayer)
...
end;

procedure TGLayer.Changed;
begin
  _Changed:=True;
  inherited;
end;

procedure TGLayer.Paint(Buffer: TBitmap32);
begin
if _Changed then
begin
    DrawPolys; // Draw bitmap for new size
   _Changed:=False;
end;

procedure TGLayer. DrawPolys;
var
  H,W:integer;
  t:TArrayOfArrayOfFloatPoint;
  ScaleX, ScaleY: TFloat;
  B:TFloatRect;
begin
  LayerCollection.GetViewportScale(ScaleX, ScaleY);
  with GetAdjustedRect(Location) do
  begin
    t:=GR32_VectorUtils.ScalePolyPolygon(Src,ScaleX, ScaleY);
    W:=Ceil(Abs(Right-Left));
    H:=Ceil(Abs(Bottom-Top));
    Bitmap.DrawMode:=dmBlend;
    Bitmap.BeginUpdate;
    Bitmap.SetSize(W,H);
    Bitmap.Clear(0);
    PolyPolylineFS(Bitmap,t,clBlack32,False);
    Bitmap.EndUpdate;
  end;
end;

and add this code to TImgView32.DoScaleChange

procedure TImgView32.DoScaleChange;
var
I:integer;
begin
  inherited;
  Buffer.BeginUpdate;
    for I := 0 to Layers.Count - 1 do
       Layers.Items[I].Changed();
  Buffer.EndUpdate();
end;

**Comment by lamdalili** [comment] 2019-05-29 10:41
this happens when you are not drawing directly on the bitmap, the use of a new event like OnScaleShiftChange is needed...
proposed code:
 
TGLayer=class(TBitmapLayer)
...
end;

procedure TGLayer.Changed;
begin
  _Changed:=True;
  inherited;
end;

procedure TGLayer.Paint(Buffer: TBitmap32);
begin
if _Changed then
begin
    DrawPolys; // Draw bitmap for new size
   _Changed:=False;
end;

procedure TGLayer. DrawPolys;
var
  H,W:integer;
  t:TArrayOfArrayOfFloatPoint;
  ScaleX, ScaleY: TFloat;
  B:TFloatRect;
begin
  LayerCollection.GetViewportScale(ScaleX, ScaleY);
  with GetAdjustedRect(Location) do
  begin
    t:=GR32_VectorUtils.ScalePolyPolygon(Src,ScaleX, ScaleY);
    W:=Ceil(Abs(Right-Left));
    H:=Ceil(Abs(Bottom-Top));
    Bitmap.DrawMode:=dmBlend;
    Bitmap.BeginUpdate;
    Bitmap.SetSize(W,H);
    Bitmap.Clear(0);
    PolyPolylineFS(Bitmap,t,clBlack32,False);
    Bitmap.EndUpdate;
  end;
end;

and add this code to TImgView32.DoScaleChange

procedure TImgView32.DoScaleChange;
var
I:integer;
begin
  inherited;
  Buffer.BeginUpdate;
    for I := 0 to Layers.Count - 1 do
       Layers.Items[I].Changed();
  Buffer.EndUpdate();
end;

**Comment by lamdalili** [comment] 2019-05-29 11:10
this happens when you are not drawing directly on the bitmap, the use of a new event like OnScaleShiftChange is needed...
proposed code:
```
TGLayer=class(TBitmapLayer)
...
end;

procedure TGLayer.Changed;
begin
  _Changed:=True;
  inherited;
end;

procedure TGLayer.Paint(Buffer: TBitmap32);
begin
if _Changed then
begin
    DrawPolys; // Draw bitmap for new size
   _Changed:=False;
end;

procedure TGLayer. DrawPolys;
var
  H,W:integer;
  t:TArrayOfArrayOfFloatPoint;
  ScaleX, ScaleY: TFloat;
  B:TFloatRect;
begin
  LayerCollection.GetViewportScale(ScaleX, ScaleY);
  with GetAdjustedRect(Location) do
  begin
    t:=GR32_VectorUtils.ScalePolyPolygon(Src,ScaleX, ScaleY);
    W:=Ceil(Abs(Right-Left));
    H:=Ceil(Abs(Bottom-Top));
    Bitmap.DrawMode:=dmBlend;
    Bitmap.BeginUpdate;
    Bitmap.SetSize(W,H);
    Bitmap.Clear(0);
    PolyPolylineFS(Bitmap,t,clBlack32,False);
    Bitmap.EndUpdate;
  end;
end;

and add this code to TImgView32.DoScaleChange

procedure TImgView32.DoScaleChange;
var
I:integer;
begin
  inherited;
  Buffer.BeginUpdate;
    for I := 0 to Layers.Count - 1 do
       Layers.Items[I].Changed();
  Buffer.EndUpdate();
end;
```

**Comment by chulwoongjeon-stemcell** [comment] 2019-05-29 16:27
I tried to roll back the 'GR32_Image.pas' to Aug 30, 2012 version.
The version in Aug 2012 didn't show any problem.

**Comment by andersmelander** [comment] 2019-05-31 12:12
@chulwoongjeon-stemcell I have reviewed the changes made to `GR32_Image` from august 30 to now and as far as I can tell none of those changes should make a difference with regard to this issue.
I really do think we will need a minimal example that reproduces the problem, like Christian requested, in order to get this problem fixed.

@lamdalili I don't understand you comment.
- Where and when should your proposed `OnScaleShiftChange` event be fired?
- `TImgView32` just exposes the design-time properties of `TCustomImgView32` as published and is not the place to fix things.
  Are you saying that the following would fix the problem (I've rearranged things a bit):
```
procedure TCustomImgView32.DoScaleChange;
var
  i: integer;
begin
  inherited;
  InvalidateCache;
  UpdateScrollBars;

  BeginUpdate; // Defer premature Changed and Invalidate in UpdateImage
  try
    UpdateImage;

    Buffer.BeginUpdate;
    try
      for i := 0 to Layers.Count - 1 do
        Layers[i].Changed;
    finally
      Buffer.EndUpdate;
    end;
  finally
    EndUpdate;
  end;
  Changed; // Calls Invalidate
end;
```

**Comment by lamdalili** [comment] 2019-06-06 13:47
Yes your code words for me... I use the above example to create new image for different resolutions

I proposed a new event 'OnScaleShiftChange'  because  some thing is wrong when using changed in line  Layers[i].Changed  .. here we force raising a possible heavy opeartions and when the scale changed is not the probleme of the Layer but it must be notified and see if any updating is needed.

      for i := 0 to Layers.Count - 1 do
        Layers[i].OnScaleShiftChange;

**Comment by andersmelander** [comment] 2019-06-06 17:19
I will implement the `DoScaleChange` modification I listed above as a solution for this issue (although I can't reproduce the problem).

With regard to your `OnScaleShiftChange` it may have merits but it's out of scope for the this release. I have create a new issue for it instead: #89.

**Comment by andersmelander** [comment] 2022-03-22 19:32
Never got an example of what the problem was, so nothing to do here.

**Closed by andersmelander** 2022-03-22 19:32 UTC
Labels: help wanted
