### ISSUE TITLE
RenderText anti alias doesn't seem to work ok

### ISSUE THREAD

**Issue by mebo** [graphics32/graphics32#179] opened 2022-03-17 16:23 UTC
We have some issues when rendering text using TBitmap32.RenderText in combination with AA.
It's quite visible when drawing a white text to a near white background, the characters have a dark edge around them, as if they are anti aliased against a dark background which isn't there.

We do this by creating a TImage32 with some layers we call RenderText() on:

procedure TMainForm.FormCreate(Sender: TObject);
begin
 fImage := TImage32.Create(self);
 fImage.Parent := self;
 fImage.Align := alClient;

 fTextLayer := TBitmapLayer.Create(fImage.Layers);
 fTextLayer.Bitmap.DrawMode := dmBlend;
 fTextLayer.Bitmap.SetSize(400,100);
 fTextLayer.Location := FloatRect(Bounds(0, 0,  fTextLayer.Bitmap.Width, fTextLayer.Bitmap.Height));
 fTextLayer.Bitmap.Font.Size := 40;
 fTextLayer.Bitmap.RenderText(10,10, 'anti aliasing = 4', 4, Color32(clwhite));

 fTextLayer2 := TBitmapLayer.Create(fImage.Layers);
 fTextLayer2.Bitmap.DrawMode := dmBlend;
 fTextLayer2.Bitmap.SetSize(400, 100);
 fTextLayer2.Location := FloatRect(Bounds(0, 200,  fTextLayer2.Bitmap.Width, fTextLayer2.Bitmap.Height));
 fTextLayer2.Bitmap.Font.Size := 40;
 fTextLayer2.Bitmap.RenderText(10,10, 'anti aliasing = 1', 1, Color32(clwhite));
end;

![Zoom in of example:](https://i.imgur.com/E9M9G4G.png)

Am I doing something wrong here?

Attached zip contains source and compiled binary which shows this behavior.
[GR32_TextRender_AA.zip](https://github.com/graphics32/graphics32/files/8288010/GR32_TextRender_AA.zip)

**Comment by andersmelander** [comment] 2022-03-17 22:22
Since you're drawing onto a transparent layer, make sure you're using the `cmBlend` [CombineMode](https://graphics32.github.io/Docs/Units/GR32/Classes/TCustomBitmap32/Properties/CombineMode.htm). so the layers will blend correctly onto the back buffer.

See also #23.

**Comment by mebo** [comment] 2022-03-18 08:03
Hi @andersmelander, thanks for your feedback.

I've tried setting the CombineMode of all 3 bitmaps to cmBlend, but no changes in result:

procedure TMainForm.FormCreate(Sender: TObject);
begin
 fImage := TImage32.Create(self);
 fImage.Parent := self;
 fImage.Align := alClient;
 fImage.Bitmap.CombineMode := cmBlend;

 fTextLayer := TBitmapLayer.Create(fImage.Layers);
 fTextLayer.Bitmap.DrawMode := dmBlend;
 fTextLayer.Bitmap.CombineMode := cmBlend;
 fTextLayer.Bitmap.SetSize(400,100);
 fTextLayer.Location := FloatRect(Bounds(0, 0,  fTextLayer.Bitmap.Width, fTextLayer.Bitmap.Height));
 fTextLayer.Bitmap.Font.Size := 40;
 fTextLayer.Bitmap.RenderText(10,10, 'anti aliasing = 4', 4, Color32(clwhite));

 fTextLayer2 := TBitmapLayer.Create(fImage.Layers);
 fTextLayer2.Bitmap.DrawMode := dmBlend;
 fTextLayer.Bitmap.CombineMode := cmBlend;
 fTextLayer2.Bitmap.SetSize(400, 100);
 fTextLayer2.Location := FloatRect(Bounds(0, 200,  fTextLayer2.Bitmap.Width, fTextLayer2.Bitmap.Height));
 fTextLayer2.Bitmap.Font.Size := 40;
 fTextLayer2.Bitmap.RenderText(10,10, 'anti aliasing = 1', 1, Color32(clwhite));
end;

**Comment by andersmelander** [comment] 2022-03-18 10:37
My bad. I meant `cmMerge` CombineMode.

> **cmMerge** - Uses a completely different formula that also merges the alpha-channels. **This mode is slower than blending but is suited for working with alpha-channels (eg. when composing in temporary buffers).** Internally uses Merge and MergeEx routines.

**Comment by mebo** [comment] 2022-03-18 12:45
I found the cause, as described in the link you gave (issue 23), it's important to clear the bitmap you're rendering text to with the color you are going to render text with but with alpha set to 0.

So this works:

procedure TMainForm.FormCreate(Sender: TObject);
begin
fImage := TImage32.Create(self);
fImage.Parent := self;
fImage.Align := alClient;

fTextLayer := TBitmapLayer.Create(fImage.Layers);
fTextLayer.Bitmap.DrawMode := dmBlend;
fTextLayer.Bitmap.SetSize(400,100);
fTextLayer.Clear(SetAlpha(clWhite32, 0));
fTextLayer.Location := FloatRect(Bounds(0, 0, fTextLayer.Bitmap.Width, fTextLayer.Bitmap.Height));
fTextLayer.Bitmap.Font.Size := 40;
fTextLayer.Bitmap.RenderText(10,10, 'anti aliasing = 4', 4, clWhite32);

fTextLayer2 := TBitmapLayer.Create(fImage.Layers);
fTextLayer2.Bitmap.DrawMode := dmBlend;
fTextLayer2.Bitmap.SetSize(400, 100);
fTextLayer2.Clear(SetAlpha(clWhite32, 0));
fTextLayer2.Location := FloatRect(Bounds(0, 200, fTextLayer2.Bitmap.Width, fTextLayer2.Bitmap.Height));
fTextLayer2.Bitmap.Font.Size := 40;
fTextLayer2.Bitmap.RenderText(10,10, 'anti aliasing = 1', 1, clWhite32);
end;

**Comment by andersmelander** [comment] 2022-03-18 13:43
> it's important to clear the bitmap you're rendering text to with the color you are going to render text with but with alpha set to 0.

That shouldn't be necessary so it's possible that there's a bug in the low level merge routines which makes it necessary. For example what would you do if you were drawing text of different colors onto the same bitmap?

By the way I would recommend that you use AALevel=-1. This uses the anti aliasing provided by Windows instead of emulating anti aliasing via supersampling. Another solution would be to use the vector based text rendering demonstrated in the issue I linked to.

Anyway, I have reproduced the problem an I'm investigating it now.

**Comment by andersmelander** [comment] 2022-03-18 14:18
Found it!
The bug was fixed in 2012 but for some reason only applied to the `RenderTextW` method. The `RenderText` method still has the bug.

Since we no longer have to support pre-unicode versions of Delphi I will merge the two methods into `RenderText` and remove `RenderTextW`.

Until then you can work around the problem by using `RenderTextW` instead of `RenderText`.

**Closed** 2022-03-18 15:50 UTC
Labels: bug

**Comment by mebo** [comment] 2022-03-21 09:25
> Found it! The bug was fixed in 2012 but for some reason only applied to the `RenderTextW` method. The `RenderText` method still has the bug.
> 
> Since we no longer have to support pre-unicode versions of Delphi I will merge the two methods into `RenderText` and remove `RenderTextW`.
> 
> Until then you can work around the problem by using `RenderTextW` instead of `RenderText`.

Thanks for the research and feedback.
As a test I took [https://github.com/graphics32/graphics32/commit/abc5c5cf0b046fbba80a34d47ac2d877dc22bb21](https://github.com/graphics32/graphics32/commit/abc5c5cf0b046fbba80a34d47ac2d877dc22bb21) and tested without calling Clear, for me that doesn't work, I get the same behavior as mentioned before, so for now I've kept the calls to Clear().

**Comment by lamdalili** [comment] 2022-03-21 18:19
I saw this problem a few years ago I was working on TBitmapLayer  in the same conditions as the current example, so it's not a bug itself but a confusing situation  since the buffer must be initialized for blending before use

`  with GetAdjustedRect(Location) do
  begin
    W:=Ceil(Abs(Right-Left)+1);
    H:=Ceil(Abs(Bottom-Top)+1);
    Bitmap.DrawMode:=dmBlend;
    Bitmap.CombineMode:=cmMerge;  
    Bitmap.BeginUpdate;
    Bitmap.SetSize(W,H);
    Bitmap.Clear($00FFFFFF); 
    DrawDsgObject(Src,Bitmap);
    Bitmap.EndUpdate;
    ...
`
![San](https://user-images.githubusercontent.com/40634105/159333619-f99b9bdc-e3ca-4010-8bed-c250d5ffa0c5.png)

I suggest the following code in Clear to fix it  ..

`procedure TCustomBitmap32.Clear;
begin
  if DrawMode=dmBlend then
     Clear(SetAlpha(clWhite32, 0))
  else
     Clear(clBlack32);
end;`

**Comment by andersmelander** [comment] 2022-03-22 10:36
@lamdalili The Clear($00FFFFFF) is only needed if CombineMode isn't set correctly. There might have been a bug earlier which made it necessary then but as I stated earlier it _shouldn't_ be required now. The formula for alpha composition using the Merge operator is:

>       Ra = Fa + Ba * (1 - Fa)
>       Rc = (Fa * (Fc - Bc * Ba) + Bc * Ba) / Ra
> 
> where
> 
> * Rc is the resultant color,
> * Ra is the resultant alpha,
> * Fc is the foreground color,
> * Fa is the foreground alpha,
> * Bc is the background color,
> * Ba is the background alpha.

Here you can see that if the background alpha _Ba_ is 0 then the background color _Bc_ value is disregarded.

    Ra = Fa + 0 * (1 - Fa)
    Rc = (Fa * (Fc - Bc * 0) + Bc * 0) / Ra

    Ra = Fa 
    Rc = (Fa * Fc) / Ra

    Ra = Fa 
    Rc = Fc

And if the foreground alpha _Fa_ is 0 then the foreground color _Fc_ value is disregarded.

      Ra = 0 + Ba * (1 - 0)
      Rc = (0 * (Fc - Bc * Ba) + Bc * Ba) / Ra

      Ra = Ba
      Rc = (Bc * Ba) / Ra

      Ra = Ba
      Rc = Bc

I have verified that this works in both 32- and 64-bit with the PAS, ASM and SSE2 implementations of MergeReg (the low level function used in this case).

Here's the code I used to test;

```
  FImage := TImage32.Create(Self);
  FImage.Parent := Self;
  FImage.Align := alClient;

  // Transparent TImage32 isn't really supported (see issue #105)
  //FImage.Bitmap.SetSize(400, 400);
  //FImage.Bitmap.Clear(clWhite32);

  FTextLayer := TBitmapLayer.Create(FImage.Layers);
  FTextLayer.Bitmap.CombineMode := cmBlend; // This is wrong
  FTextLayer.Bitmap.DrawMode := dmBlend;
  FTextLayer.Bitmap.SetSize(400,100);
  FTextLayer.Bitmap.Clear($00FFFFFF); // But this makes it work anyway
  FTextLayer.Location := FloatRect(Bounds(0, 0,  FTextLayer.Bitmap.Width, FTextLayer.Bitmap.Height));
  FTextLayer.Bitmap.Font.Size := 40;
  FTextLayer.Bitmap.RenderText(10,10, 'XLorem Ipsum', -1, clWhite32);

  FTextLayer2 := TBitmapLayer.Create(FImage.Layers);
  FTextLayer2.Bitmap.CombineMode := cmMerge; // This is correct
  FTextLayer2.Bitmap.DrawMode := dmBlend;
  FTextLayer2.Bitmap.SetSize(400, 100);
  FTextLayer2.Bitmap.Clear(0); // This really doesn't matter
  FTextLayer2.Location := FloatRect(Bounds(0, 200,  FTextLayer2.Bitmap.Width, FTextLayer2.Bitmap.Height));
  FTextLayer2.Bitmap.Font.Size := 40;
  FTextLayer2.Bitmap.Font.Style := [fsItalic];
  FTextLayer2.Bitmap.RenderText(10,10, 'XLorem Ipsum', -1, clWhite32);
```
Note that both layers render the AA correctly, but that the first one incorrectly uses `CombineMode=cmBlend` and therefore has to use `Clear($00FFFFFF)`.

**Comment by lamdalili** [comment] 2022-04-01 19:14
Thanks for the  detailed explanation which makes the transparency clearer ..
this solves my problem ; I found that I should do the same settings with the original Bitamp because TBitmapLayer here is just a thumbnail ...thanks
