### ISSUE TITLE
Copy to clipboard, image got shifted 

### ISSUE THREAD

**Issue by huyi7** [graphics32/graphics32#257] opened 2023-07-08 12:23 UTC
I found that if I copy an image with alpha to clipboard, the image is shifted by 3 pixels to the left. It means the data is shifted by 12 bytes. 
In GR32, TCustomBitmap32.SaveToDIBStream(), lin 6114,
 if I comment out “(InfoHeaderVersion < InfoHeaderVersion2)” in line 
  if //(InfoHeaderVersion < InfoHeaderVersion2) and
  (Header.InfoHeader.biCompression = BI_BITFIELDS) then
 the image copied is correct. I wonder if it's really due to we omitting those 12 bytes, even if our header version is not 1.

**Comment by andersmelander** [comment] 2023-07-08 12:39
Please attach the original bitmap and the bitmap after it has been saved by Graphics32.

**Comment by andersmelander** [comment] 2023-07-08 13:26
Okay, I was a bit too quick there and didn't read your description properly.

What you're saying is that the extra 12 bytes should always be added, regardless of `InfoHeaderVersion`and `InfoHeader.biCompression`.

I'll have to disagree about that (the 12 bytes are already included for `InfoHeaderVersion` > 1) and I haven't been able to reproduce the problem you're describing.

What application are you pasting the copied bitmap to?

**Comment by huyi7** [comment] 2023-07-08 13:51
Thanks for your quick response. 

[TestCopyClipboard.zip](https://github.com/graphics32/graphics32/files/11990779/TestCopyClipboard.zip)
I've attached a test app. You click 'Copy' to copy the image to the clipboard. Then, use any image editor to paste the image. I use Paint.NET and the outcome is attached in a screenshot:
![image](https://github.com/graphics32/graphics32/assets/10126904/8bddb5b6-1fcb-48b1-93a6-baf1aaacd6dd)
The ellipse on the left should have been just touching the left edge of the image, but it now wraps around.

Original image attached:
![test_gr32_copy_clipboard](https://github.com/graphics32/graphics32/assets/10126904/9b95d4b5-6caf-4051-a7fc-4eb65be01914)

**Comment by andersmelander** [comment] 2023-07-08 16:33
Works for me.
![billede](https://github.com/graphics32/graphics32/assets/18141921/367c0c9c-ad5f-4bf3-bf19-2f4246058952)

This could very well be a bug in Paint.NET (or whatever library Paint.NET uses to read bitmaps). Very few applications handle 32-bit RGBA bitmaps correctly.

**Comment by andersmelander** [comment] 2023-07-08 19:36
If you attach a 32-bit RGBA bitmap saved by Paint.NET I can examine it to determine how it structures the BMP header. Maybe that will provide some clues.

**Comment by huyi7** [comment] 2023-07-10 15:09
I take back my words of using *any* image editor. :) To test properly we need one that reads the DIBV5 image with alpha.
I think MS Paint doesn't get the RGBA image stored as DIBV5 bitmap in the clipboard, but it reads the DIB bitmap without alpha also copied by CopyBitmap32ToClipboard().
Not sure why you can get the image pasted to GIMP, while for me GIMP 2.10.34 (latest) won't paste anything from the test program. (I tried copying a PNG image to clipboard by code, and GIMP is able to copy from the PNG) 
I tried Krita, and pasting with alpha gives shifting. 
I tried Affinity Photo, and pasting with alpha is correct without shifting.  <- so at least I found one app that reads the image with alpha correctly! 
I tried Photoshop. It gets the no-alpha version of the image. :(  
I am using this https://freeclipboardviewer.com/windowsclipboard/ to see what are currently in the clipboard.

Attached is a 32-bit bitmap saved by Paint.NET. This forum doesn't allow .BMPX, so I zipped it.
[test_gr32_copy_clipboard.zip](https://github.com/graphics32/graphics32/files/12003459/test_gr32_copy_clipboard.zip)

**Comment by rickbrew** [comment] 2023-07-11 20:22
> Apparently Paint.NET uses WIC to load/save BMPs but fails to set the correct encoding options:

That doesn't sound accurate to me. There are really only two options for BMP when working in WIC: the pixel format, and the `EnableV5Header32bppBGRA` option which makes it possible to save with alpha.

In either case, WIC is not used for parsing bitmaps from the clipboard.

See here for @0xC0000054 's analysis of this bug report: https://forums.getpaint.net/topic/122848-pasting-dibv5-image/?do=findComment&comment=610904

> The issue appears to be that Graphics32 fails to write the 3 DWORD color masks after the header that are required for 32-bit bitmaps that use BI_BITFIELDS compression.

**Comment by andersmelander** [comment] 2023-07-11 22:35
> See here for @0xC0000054 's analysis of this bug report: https://forums.getpaint.net/topic/122848-pasting-dibv5-image/?do=findComment&comment=610904

Here's my response: https://forums.getpaint.net/topic/122848-pasting-dibv5-image/#comment-610918

**Comment by rickbrew** [comment] 2023-07-12 01:42
This does look like a genuine bug in Paint.NET. It hasn't come across my radar because, as far as I can tell, `CF_DIBV5` with `BI_BITFIELDS` is no longer a commonly used clipboard format. Paint.NET has its own code for parsing `CF_DIBV5`, but it only uses it for 32-bit images with alpha.

I only found Remote Desktop and Krita using `CF_DIBV5` + `BI_BITFIELDS`. Remote Desktop's bitmap doesn't contain alpha, so our custom CF_DIBV5 parsing code wasn't being used, and Krita puts a `CF_DIB` that happened to work correctly so it wasn't an issue (the `CF_DIBV5` code rejected it because the size was "wrong" ... aka correct).

Barring any further complications, this should be fixed in Paint.NET 5.0.8. Should be later this month.

**Comment by andersmelander** [comment] 2023-07-12 02:12
@rickbrew Thanks for getting back to me on this. I'll close this issue here.

**Comment by andersmelander** [comment] 2024-02-06 11:40
Reopening this issue as evidence now appears to support that the Graphics32 handling of the BI_BITFIELD format in [BITMAPV4HEADER](https://learn.microsoft.com/en-us/windows/desktop/api/Wingdi/ns-wingdi-bitmapv4header) and [BITMAPV5HEADER](https://learn.microsoft.com/en-us/windows/desktop/api/Wingdi/ns-wingdi-bitmapv5header) is incorrect.

See: https://forums.getpaint.net/topic/124628-1-px-line-on-top-of-every-image-pasted-into-firefox-from-paintnet/?do=findComment&comment=621249

**Closed** 2024-02-06 17:07 UTC
Labels: bug

**Comment by rickbrew** [comment] 2024-02-08 00:46
See my most recent analysis here: https://forums.getpaint.net/topic/124628-1-px-line-on-top-of-every-image-pasted-into-firefox-from-paintnet/?do=findComment&comment=621636

The tl;dr is that this is what I've concluded\* :
- For 32-bpp BGRA .BMP storage with `BITMAPV5HEADER` and `BI_BITFIELDS`, the 3 extra bitmasks should be included.
- For a 32-bpp BGRA DIBV5 copied to the clipboard, with `BITMAPV5HEADER` and `BI_BITFIELDS`, the 3 extra bitmask should _not_ be included.

Don't ask me why just get me some aspirin.

\* at least until we find evidence to the contrary

**Comment by andersmelander** [comment] 2024-02-09 15:24
> There's still a problem with pasting to Firefox.

It's a bug in Firefox:

**CF_DIBV5 with color table**

| MSPaint | Firefox |
| -------- | ------- |
| ![billede](https://github.com/graphics32/graphics32/assets/18141921/79734d01-ddb8-4d6b-9b86-8e4487639c25) | ![billede](https://github.com/graphics32/graphics32/assets/18141921/06862ee4-e504-42c3-93f2-6c3274dbcb74) |

**CF_DIBV5 without color table**

| MSPaint | Firefox |
| -------- | ------- |
| ![billede](https://github.com/graphics32/graphics32/assets/18141921/2a9b1f51-5841-4fcb-a823-33265a18c3fc) | ![billede](https://github.com/graphics32/graphics32/assets/18141921/2bac8275-683b-4985-b1e0-eeff8b9c7912) |

Here's the Firefox implementation of `CF_DIBV5` `BI_BITFIELDS` decoding:
https://searchfox.org/mozilla-central/source/image/decoders/nsBMPDecoder.cpp#641

```
if (mH.mBIHSize >= InfoHeaderLength::WIN_V4) {
  // Bitfields are present in the info header, so we can read them
  // immediately.
  mBitFields.ReadFromHeader(aData + 36, /* aReadAlpha = */ true);

  // If this came from the clipboard, then we know that even if the header
  // explicitly includes the bitfield masks, we need to add an additional
  // offset for the start of the RGB data.
  if (mIsForClipboard) {
    mH.mDataOffset += BitFields::LENGTH;
  }
...
```

**Comment by rickbrew** [comment] 2024-02-09 17:46
I wouldn't expect GIMP to be using WIC for reading BMPs -- how would that work on Linux? 🤔

It makes sense that BMP files could be made to work w/ or w/o the 3 masks because of the `bfOffBits` field in `BITMAPFILEHEADER`. It tells you exactly where to go! But, the clipboard doesn't get the benefit of that field, and the documentation is a weird blend of both scenarios (disk vs. clipboard) that never really lays out any expected differences or consequences.

It's probably too much to expect to be able to include the color profile data in there, _certainly not_ for transport via the clipboard. I have some experimental code for this but ... eh, it works but nothing else recognizes the color profile so there's really no point.

**Comment by andersmelander** [comment] 2024-02-09 18:12
> I wouldn't expect GIMP to be using WIC for reading BMPs -- how would that work on Linux? 🤔

Not everything has to be platform independent. Some things can be delegated to platform components. E.g I suspect that much of the font handling in Gimp is using whatever features the OS provides.

> It makes sense that BMP files could be made to work w/ or w/o the 3 masks because of the bfOffBits field in BITMAPFILEHEADER. It tells you exactly where to go!

Yes it does, but nobody seems to rely on that field - And yet in this case it appears to make all the difference.
Most implementations I've seen just read the fileheader to validate the "BM" marker and then skip it to read the rest as a DIB.

> It's probably too much to expect to be able to include the color profile data in there

Color profile? I've never seen anything use that. Why are you bringing that up?

**Comment by rickbrew** [comment] 2024-02-09 19:01
> Color profile? I've never seen anything use that. Why are you bringing that up?

I've recently added color management to PDN for an upcoming release (v5.1). BMPs can contain embedded profiles, so I looked into (and implemented) this, but the logic/spec for it is another layer of confusion. It seems that it can either go between the header and the bitmap, or after the bitmap, and the documentation can't seem to make up its mind about it.

from [`BITMAPV5HEADER`](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapv5header):

> When a DIB is loaded into memory, the profile data (if present) should follow the color table, and the bV5ProfileData should provide the offset of the profile data from the beginning of the BITMAPV5HEADER structure. The value stored in bV5ProfileData will be different from the value returned by the sizeof operator given the BITMAPV5HEADER argument, because bV5ProfileData is the offset in bytes from the beginning of the BITMAPV5HEADER structure to the start of the profile data. (Bitmap bits do not follow the color table in memory). Applications should modify the bV5ProfileData member after loading the DIB into memory.
>
> For packed DIBs, the profile data should follow the bitmap bits similar to the file format. The bV5ProfileData member should still give the offset of the profile data from the beginning of the BITMAPV5HEADER.

Let's break this down:

> When a DIB is loaded into memory, the profile data (if present) should follow the color table

Okay so it goes after the color table, which is before the bitmap bits

> (Bitmap bits do not follow the color table in memory)

What? Then where do they go?!

> Applications should modify the bV5ProfileData member after loading the DIB into memory.

Modify it how?!

> For packed DIBs, the profile data should follow the bitmap bits similar to the file format.

Now they say it goes after the bitmap bits 🤔

Now let's look at [Bitmap Header Types](https://learn.microsoft.com/en-us/windows/win32/gdi/bitmap-header-types):

> Profile data refers to either the profile file name (linked profile) or the actual profile bits (embedded profile). The file format places the profile data at the end of the file. The profile data is placed just after the color table (if present). However, if the function receives a packed DIB, the profile data comes after the bitmap bits, like in the file format.
> 
> Profile data will only exist for [BITMAPV5HEADER](https://learn.microsoft.com/en-us/windows/desktop/api/Wingdi/ns-wingdi-bitmapv5header) structures where bV5CSType is PROFILE_LINKED or PROFILE_EMBEDDED. For functions that receive packed DIBs, the profile data comes after the bitmap data.

Here they're also saying "... at the end of the file", "... after the color table", as well as "... after the bitmap bits."

So it's defined very clumsily, but the profile data (the actual color profile bytes) should probably be placed after the bitmap bits. But they really don't make it simple to reach that conclusion unambiguously.

The combination of `BITMAPFILEHEADER.bfOffBits` and `BITMAPV5HEADER.bV5ProfileData` ("The offset, in bytes, from the beginning of the BITMAPV5HEADER structure to the start of the profile data") would imply a flexibility in placing the color profile before or after the bitmap bits. The documentation is sometimes clear about the differences between "in memory" versus "file format", but not always.

**Comment by andersmelander** [comment] 2024-02-09 19:50
I've always read the documentation as _the profile data goes after the bitmap bits_. This is probably another case of too many edits to the documentation because the last time I read it, which admittedly was many years ago, there was no ambiguity.

Interesting that there's a reference to "packed DIBs". I've seen that mentioned a few other places but no explanation of what constitutes a packed or an unpacked DIB.

**Comment by rickbrew** [comment] 2024-02-09 21:34
> Interesting that there's a reference to "packed DIBs". I've seen that mentioned a few other places but no explanation of what constitutes a packed or an unpacked DIB.

From [Wikipedia](https://en.wikipedia.org/wiki/BMP_file_format) under "DIBs in memory":

> When the size of gap1 and gap2 is zero, the in-memory DIB data structure is customarily referred to as "packed DIB" ...
> ...
> "Packed DIBs" are required by [Windows](https://en.wikipedia.org/wiki/Microsoft_Windows) clipboard API functions as well as by some Windows patterned brush and resource functions.

Just above it, in the last row and column of the File structure table:

> ICC color profile ...
> ... When loaded in memory as "non-packed DIB", it is located between the color table and Gap1.

¯\\_(ツ)_/¯

**Comment by andersmelander** [comment] 2024-02-09 21:54
> I'm wondering if there's something else going on. IrfanView exhibits the exact same behavior and it would be a pretty strange coincidence if both Windows and IrfanView had the same bug.

Yup. It was a bug on my part. Fixed and now all test bitmaps display correctly in Windows and IrfanView.
