### ISSUE TITLE
Path.arc always closes path

### ISSUE THREAD

**Issue by TomyN** [graphics32/graphics32#3] opened 2016-11-08 18:08 UTC
Hi,
I'm not sure if this is a bug or planned behavior.
canvas32.path.arc closes the path and ends the current path. So it acts like rectangle or circle (where this would make sense), but in my opinion the arc function should be able to integrate in a path to allow geometric figures. 
This behavior is due to the use of the TCustomPath.polygon function in arc. 
I just created a second version of arc, which calls a function called 'Polyline' where polyline does neither call ClosePath nor EndPath and the call to BeginPath is optional.

Tomy

**Comment by AngusJohnson** [comment] 2016-11-27 13:10
Hi TomyN.
I agree with you that TCustomPath.Arc() should not force path closure as it currently does. I would suggest adding a Closed: Boolean = true parameter to this method. And perhaps TCustomPath (and TFlattenedPath) should have a Polyline methods that doesn't call ClosePath either before or after adding APoints to the path. Perhaps others may wish to comment before I commit any changes.

**Comment by TomyN** [comment] 2016-11-27 13:29
HI Angus,

thanks for your post. I think that adding one (or more) parameter would make the whole thing more complicated, because if you want to continue with this path you need to avoid the EndPahth statement also (and might be that the arc is not the start of the path.... ). So I'd think that it would make more sense to publish just the routine that adds the points to the path (BuildArc) without BeginPath and EndPath, so you can use it as part of your path.
By the way, what's a FlattendedPath?

Tomy

**Comment by AngusJohnson** [comment] 2016-11-27 16:27
Hi again Tomy.
I'm also keen to keep the library as simple as possible, but do you really think a separate Arc method (BuildArc) is less complicated? I'm not yet persuaded to that approach either.

> By the way, what's a FlattendedPath?
https://github.com/graphics32/graphics32/blob/master/Source/GR32_Paths.pas#L107

**Comment by AngusJohnson** [comment] 2016-11-27 16:36
Another approach might be to change Arc to an open path method, leaving the end user the responsible for closing  if they wish.

**Comment by TomyN** [comment] 2016-11-27 20:47
Hi again Angus,

I'd like that. 
And might be that somebody creates an other unit with some suffixes (like on the canvas draw routines) with C (Closing), B (Begin path) and E (End path), where the current version would be ArcBCE

**Comment by micha137** [comment] 2017-10-27 15:55
Any news on this? Either Angus commits a change or Tomy submits a pull request... sorry, no comments on the content, since I don't use that function...

**Comment by uparlayan** [comment] 2018-05-06 14:49
![image](https://user-images.githubusercontent.com/24311198/39674500-89c41f0c-5155-11e8-8296-692d5a01b0da.png)

Hello there;

How do I draw a geometric arc like the one above? The BuildArc function does not behave as expected.

**Comment by AngusJohnson** [comment] 2019-04-02 12:43
As far as I can see, this issue is still unresolved. 

I believe TFlattenedPath's ClosePath method is confusing. To me, this method implies joining the start and end points of a path, whereas what it seems to do is what I would expect EndPath to do (ie stop further points being added to the current path). If Mathias was around I would defer to his wisdom on this as he is the original author. Failing Mathias' attention, I'd be happy to modify this - making EndPath do what ClosePath currently does, and make ClosePath, join the start and end points and then call ClosePath internally.

**Comment by andersmelander** [comment] 2019-04-02 13:05
I concur.
From what I've found in the newsgroup archive the pattern to construct a single closed polygon with TFlattenedPath is or used to be:
```
BeginPath;
  ...AddPoint()...
  ClosePath;
EndPath;
```

Incidentally, if the above is correct then it seems there's a bug in `TFlattenedPath.Polygon`:
```
ClosePath;
  ...AddPoint()...
  ClosePath;
EndPath;
```
or maybe I'm not understanding what Polygon is supposed to do?

**Comment by AngusJohnson** [comment] 2019-04-02 22:10
OK, I've updated Gr32_Paths.

Here's the logic of TCustomPath / TFlattenedPath as I see it:

**TCustomPath** is an abstract base class to implement building of various paths both open and closed - rectangles, ellipses, arcs, bezier curves etc.

**TFlattenedPath** is derived from TCustomPath and creates drawable paths accessed through it's **Path** property. _TFlattenedPath.Path (TArrayOfArrayOfFloatPoint) actually represents a collection of paths and my preference would be to rename this property Paths to reflect this._

Anyhow, an example:

```
  path := TFlattenedPath.Create;
  try
  
    //Paths are initially constructed in a buffer, and will only be finalized
    //(ie accessible via 'Path') once EndPath has been called. Hence EndPath is
    //required (either implicitly via a subsequent call to BeginPath or MoveTo()
    //or ClosePath, or explicitly as demonstrated here)...

    path.BeginPath; //optional, and will close an unclosed path
    path.MoveTo(100,100); //optional, and also closes an unclosed path
    path.Arc(FloatPoint(100,100), -PI*2, -PI/2, 100);
    path.LineTo(100,100);
    path.EndPath;
    
    //and additional paths can also be constructed ...

    path.Rectangle(FloatRect(0,0,200,200));
    
    //Note: a number of methods (eg Rectangle, Ellipse, Polygon etc) implicitly
    //create closed paths, and these will call BeginPath and EndPath internally.

    //finally use (draw) the path ...
    PolyPolylineFS(image.Bitmap, path.Path, clBlack32, false, 2);
    
  finally
    path.Free;
  end;

```

**Comment by andersmelander** [comment] 2019-04-03 11:57
Thanks for the explanation. I needed that because I think the TFlattenedPath design is pretty confusing. I mean I get the concept that TFlattenedPath is a collection of paths, but the API as it is now leaves too much opportunity for errors as it isn't clear from the API which methods alters what state and how. Just the fact that there is different levels of state involved should indicate that something's wrong. More on that later...

Anyhow, I've got a few Qs:
- Why do we have a TCustomPath abstract base class? What other kinds of paths could we have besides TFlattenedPath?
- Why is it called TFlattenedPath?
- Is TFlattenedPath.DrawPath actually implemented anywhere?

Apart from that I noticed that TFlattenedPath breaks encapsulation in a couple of places by accessing the private FCurrentPoint of the base class. Also the use of "with" in TFlattenedPath.AssignTo is really bad for the readability (and my OCD).

Back to the state. The problem as I see is that we have some methods that operate on the Path collection (most but not all of TFlattenedPath) and some that operate on the "current" path (TCustomPath). I can't see a good way of solving this without a complete redesign of these classes. This could separate the functionality that constructs a path from the functionality that manage paths. However a more "pure" design might not warrant the cost of implementation and the overhead it would involve. Probably not.

Agree on the Path->Paths by the way.

**Comment by AngusJohnson** [comment] 2019-04-03 12:44
> Why do we have a TCustomPath abstract base class? 

You'd need to ask Mattias, who is the original author.

> What other kinds of paths could we have besides TFlattenedPath?

Nothing comes to mind and it would certainly simply things to amalgamate the 2 classes.

> Why is it called TFlattenedPath?

'Flattening' is the process of approximating curves as series of straight edges. I don't have any real problem with the name, can you think of a better one?
See also https://docs.microsoft.com/en-us/windows/desktop/gdiplus/-gdiplus-flattening-paths-about

> Is TFlattenedPath.DrawPath actually implemented anywhere?

No, it doesn't appear to be, and I'd be happy to see it removed. I also need to be persuaded of the benefit of TCanvas32, and whether it should be moved to it's own unit. And I don't understand the logic behind calling BeginPath and EndPath in TFlattenedPath.AssignTo().

There may well be good reasons for many of these things but we'd need Mattias' input to be sure. And I imagine we've all released code that has been somewhat rushed into service, code that benefits from peer review. I know only too well when I look at much of my own code later on how poorly it reads, and how I can still do so much better with a little more patience with refactoring and documenting.etc. And I do very much value constructive feedback too.

**Comment by andersmelander** [comment] 2019-04-03 15:49
Thanks for the pointer to the GDI+ docs. That explained a lot; Both the name and the design because it appears that it was modeled after GDI+ which apparently has the same design wrt state and poor separation between layers of responsibility.

> TCanvas32

I have no clue. Seems to be a work in progress. A few comments would certainly have helped... :-)

> And I don't understand the logic behind calling BeginPath and EndPath in TFlattenedPath.AssignTo().

The only reason I can think of would be to have the destination event handlers called.

**Comment by AngusJohnson** [comment] 2019-04-07 23:56
I'm in the process of updating `TPath` (ie `TCustomPath` & `TFlattenedPath`) and have encountered several problems with no obvious solutions.

The main problem is that `TPath.Path` (returning a `TArrayOfArrayOfFloatPoint`) provides no indication as to whether each contained `TArrayOffFloatPoint` is open or closed. If the class was designed such that it was obvious that returned paths are all open or all closed this would be fine, but unfortunately this isn't the case here. This highly problematic situation is exposed in `TCanvas32.DrawPath` which assumes all completed paths (ie in `TCanvas32.Path.Path`) are closed. This assumption is plainly wrong. Also, `TCanvas32` calls its `DrawPath` method whenever a path is closed, so previously closed paths are redrawn. 

I see 3 possible solutions:
1. Redesign `TPath` such that it only contains and returns a single path (`TArrayOffFloatPoint`). This would be problematic for the `GR32_Text` units where multiple `TPath` objects would complicate the code.
2. Provide a Boolean array (eg `Closed: TArrayOfBoolean`) that parallels the `Path` array. This would be the least disruptive to existing code, but it doesn't solve the problem of open and closed paths being mixed in together. This is problematic for functions such as `PolyPolygonFS` that require multiple paths to determine holes. (IOW multiple calls to `PolygonFS` would not be a valid alternative.)
3. My preferred option would be the following:
3a. separate `FPath` into two members `FPathClosed` and `FPathOpen`.
3b: replace the Path property with `TPath.PathsOpen` and `TPath.PathsClosed` (or `TPath.OpenPaths` and `TPath.ClosedPaths`).
3c. Remove the `Points` property and treat `FPoints` solely as a private buffer.
3d. Fix up `TCanvas32` so that `TCanvas32.DrawPath` is called explicitly when the contained open and closed paths need drawing. 
3e. Remove the `TPath.OnBeginPath` and `TPath.OnEndPath` events. I question their value (and the only place they're being used in the library (incorrectly IMHO), is in the problematic `TCanvas32.DrawPath`.

**Comment by andersmelander** [comment] 2019-04-08 18:33
I don't think I've ever used `TCanvas32` or `TFlattenedPath` so I can't really comment on how they're used or how they could be improved, but from your description is does sound like option 3 is the best way forward.

However I'm against making `TCanvas32` descend from `TPath`; The purpose of `TCanvas32` is rendering and the purpose of `TPath` is management and construction of paths. `TCanvas32` isn't a specialization of `TPath`.

**Comment by AngusJohnson** [comment] 2019-04-08 20:37
> The purpose of TCanvas32 is rendering and the purpose of TPath is management and construction of paths. TCanvas32 isn't a specialization of TPath.

I agree with you in principle. However in practice it makes TCanvas32 much more cumbersome to use as I'll try to demonstrate below. Also, the current TFlattenedPath has a DrawPath method (unimplemented) which kind of hints that there's benefit in combining construction and rendering. And if you consider TCanvas, so many of it's methods relate to path construction, not simply rendering.

To me, this makes much more sense ...
```
  Canvas.BeginPath;
  Canvas.MoveTo(10,10);
  Canvas.LineTo(100,100);
  Canvas.EndPath;
  Canvas.Ellipse(100,100, 50,50);
  Canvas.Rectangle(FloatRect(10,10, 110,110));
  Canvas.Draw;
```
than ..
```
  Canvas.Path.BeginPath;
  Canvas.Path.MoveTo(10,10);
  Canvas.Path.LineTo(100,100);
  Canvas.Path.EndPath;
  Canvas.Path.Ellipse(100,100, 50,50);
  Canvas.Path.Rectangle(FloatRect(10,10, 110,110));
  Canvas.Draw;
```

**Comment by andersmelander** [comment] 2019-04-08 21:26
Apart from `LineTo()` and `MoveTo()` I can't see much path construction going on in `TCanvas`. Pretty much everything is rendering... What am I missing?

Of your two examples I would prefer the second (i.e. using `Canvas.Path`) and I don't think it's cumbersome. The recent discussion in Delphi-PRAXIS re: [composition over inheritance](https://en.delphipraxis.net/topic/907-prefer-composition-over-inheritance-for-code-reuse/) is relevant here FWIW.
I even think that I would prefer having Paths extracted from `TCanvas32` but without knowing what the idea behind the concept was originally it's a bit hard to know how to twist this thing.

**Comment by AngusJohnson** [comment] 2019-04-08 21:48
> Pretty much everything is rendering

The only rendering statement is `Canvas.Draw`.

> What am I missing?

Pretty much everything else :).
This is also path construction ...
```
  Canvas.Ellipse(100,100, 50,50);
  Canvas.Rectangle(FloatRect(10,10, 110,110));
```

ISTM the purpose of `TCanvas32` (and pretty much any canvas) is to have a context which combines everything needed to make drawing as simple as possible, and this includes path construction, stroke and fill brushes, and even font settings. And `TCanvas32` seems to do a pretty reasonable job of that.

**Comment by andersmelander** [comment] 2019-04-08 22:07
Aren't you confusing `TCanvas` (the Delphi RTL class) with `TCanvas32` (the graphics32 class)?

In `TCanvas` the `Draw()` method **renders** a bitmap onto to a "canvas" (i.e. a Win32 HDC mostly) via `TGraphic.Draw()`, the `Ellipse()` method **renders** an ellipse directly via the GDI `ellipse` function and the `Rectangle()` method **renders** a rectangle directly via the GDI `rectangle` function.

If all the path construction methods where to be moved to `TCanvas32` (e.g. by inheritance) modified to have implicit `BeginPath`/`EndPath` so they would be rendered immediately, then `TCanvas32` would behave like `TCanvas` - but is that what we want? Don't we still want to be able to "batch" construct paths and have them rendered at the end of the batch?

**Comment by AngusJohnson** [comment] 2019-04-08 22:58
> Aren't you confusing `TCanvas` with `TCanvas32`. 

Not really. `TCanvas` methods combine construction with rendering, whereas `TCanvas32` does not. So where `TCanvas.Rectangle` constructs and renders, `TCanvas32.Rectangle` only constructs and `TCanvas32` rendering is done after all construction has been completed via `TCanvas32.Draw`.

**Comment by AngusJohnson** [comment] 2019-04-09 02:59
Re: `TCanvas32.DrawPath(Path: TPath)` ... this may possibly be a better approach as it would allow `TCanvas32` to manage drawing multiple `TPath` objects with modifications to pen and fill brushes settings between each `PathDraw`. 

Also, I'm wondering if `TPaths` rather than `TPath` might be more appropriately descriptive, but then again `TPaths` could imply there's also a `TPath`.

**Comment by andersmelander** [comment] 2019-04-09 22:06
> Though, what I want to mention here is the HTML5 canvas

Thanks for that. Most educating.

I have created an implementation based on what I outlined above. Generally the design looks OK, but there are a few things that I hadn't thought of and which I''ll have to sort out.

There's also the question of backward compatibility. `TCanvas32` is used in a couple of the examples (notably the SvgPath example) and `TFlattenedPath` and `TCustomPath` in the `TextToPath` functions.

**Comment by AngusJohnson** [comment] 2019-04-09 23:27
> I have created an implementation based on what I outlined above.

Great. I look forward to seeing it.

> There's also the question of backward compatibility. 

I personally wouldn't worry too much about that given that Graphics32 ver 2 still hasn't been officially released. To me, it's much more important that the class is well designed.

Also, on a semi related note, I've been playing around with text rendering as ISTM that the current font rendering in Graphics32 can also be improved. I've adapted some code for my own mini graphics library that IMHO it produces clearer and less bold text especially with smaller font sizes. I'll tidy up the demo a bit more and will post it here later for your comments. 
![temp2](https://user-images.githubusercontent.com/5280692/55841497-bace6a80-5b72-11e9-98f0-d664370e2bbc.png)

**Comment by CWBudde** [comment] 2019-04-10 08:11
> I personally wouldn't worry too much about that given that Graphics32 ver 2 still hasn't been officially released. To me, it's much more important that the class is well designed.
I agree. Although I already use it in several projects, the changes are not really critical. I guess in the end it's a matter of some search&replace operations.

Luckily the compiler will complain about most of the changes. The most annoying breaking change is when the code still compiles, but doesn't really work anymore. For example the change from PAnsiChar to PWideChar in Delphi was kind of a nightmare with legacy code, where AnsiChar and Byte were used synonymously.

**Comment by andersmelander** [comment] 2019-04-10 23:32
Well I scrapped my initial version and started over. The new version maintains all four existing classes, `TCustomPath`, `TFlattenedPath`, `TCustomCanvas` and `TCanvas32`, but `TCustomCanvas` now derives from `TFlattenedPath`.

I have so far maintained full backward compatibility. The `Path` property has been changed to a function and marked deprecated; It just returns `self`.

The most interesting result of this endeavor has been the discovery of multiple nasty bugs. The first one I knew of already: `TCanvas32` didn't clear the path once it had been drawn which meant that the changes just accumulated inside it and old paths were drawn again and again every time a new was added. A side effect of this was that the Polygon Render Benchmark didn't actually benchmark the renderers - It benchmarked the memory manager.
For example on my system running the Ellipses test with the VPR renderer executed 79 ops/s. When I fixed the "draw doesn't clear" bug it executed 4950 ops/s... Text test before: 9 ops/s, after: 520 ops/s.

Another result from fixing this bug was that it surfaced some bugs in the VPR2, VPR2X and AggLite renderers. Simply because it now managed to process a wider selection of random test data (the test is time limited). I have fixed the AggLite bug. I'll create issues for the others once I've had some sleep.

Regarding the redesign of the `BeginPath`/`EndPath`: I dropped support for nested operations as they simply didn't make any sense. The way I see it now `MoveTo*` is just a special `BeginPath` and `ClosePath` is just a special `EndPath` so I have made `BeginPath` and `ClosePath` deprecated. `BeginPath` is now performed automatically when the first point is added to a new path and `ClosePath` is handled via the `Close` parameter to `EndPath`.

**Comment by AngusJohnson** [comment] 2019-04-10 23:48
Anders, I agree with all of your proposed changes though I'm not sure why you're keeping `TCustomPath `as I can't imagine any `TPath `other than a `TFlattenedPath` descendant.

**Comment by andersmelander** [comment] 2019-04-11 13:28
Last three commits should have been a Pull Request but evidently I can't figure out how to do that with SourceTree.
Anyway; Give it a spin.

I've left a couple of TODOs in the source. Please review.
I also need someone to verify that the LCL and D2D TextToPath functions still works. The changes in them are identical to the VCL part but I have not tested them.

> I'm not sure why you're keeping TCustomPath as I can't imagine any TPath other than a TFlattenedPath descendant.

I'm not sure either but doing so didn't affect the implementation and since I think I might have a vague idea of the original purpose of the class design I kept that part more or less untouched.

**Comment by AngusJohnson** [comment] 2019-04-11 13:45
> > I'm not sure why you're keeping TCustomPath as I can't imagine any TPath other than a TFlattenedPath descendant.
> 
> I'm not sure either but doing so didn't affect the implementation and since I think I might have a vague idea of the original purpose of the class design I kept that part more or less untouched.

Actually, on further reflection, it's possible someone might want to create a non-flattened path (eg TSvgPath) that defines curves using control points.

> Anyway; Give it a spin.

Will do :).

**Comment by AngusJohnson** [comment] 2019-04-12 00:49
Anders, I've given your new Paths and TCanvas32 a decent test drive and it's a definitive improvement on the previous incarnation. However there are still a number of issues to resolve.
1. `TCanvas32.Polyline` doesn't update FChange so EndUpdate doesn't force a redraw. I suggest dropping the BeginUpdate/EndUpdate and instead call EndPath(false) in that method.
2. There's no TCanvas32.PolyPolygon method which is often needed for polygon filling.
3. There's no TCanvas32.PolyPolyline method just to make things easier.
4. Importantly, there's still no way to differentiate open and closed paths. I propose that we add a new TEndStyle - to accommodate this. ie TEndStyle = (esButt, esSquare, esRound, esClosed);
Then in TCanvas32 we could do the following ...

```
procedure TCanvas32.DrawPath(const Path: TFlattenedPath);
  ...
  for i := 0 to FBrushes.Count-1 do
    if not FBrushes[i].Visible then Continue
    else if FBrushes[i] is TStrokeBrush then
      FBrushes[i].PolyPolygonFS(Renderer,
        Path.Path, ClipRect, Transformation,
        TStrokeBrush(FBrushes[i]).EndStyle = esClosed)
    else
      FBrushes[i].PolyPolygonFS(Renderer,
        Path.Path, ClipRect, Transformation, True);
end;
```

Also, in `GR32_Brushes`, I recommend that in the `TStrokeBrush` constructor we add `FFillMode := pfWinding;` as the pfAlternate looks odd when the stroke overlaps itself.

Here's an updated Polygons sample that demonstrates this...

[Polygons.zip](https://github.com/graphics32/graphics32/files/3071160/Polygons.zip)

**Comment by AngusJohnson** [comment] 2019-04-12 05:39
>`TCanvas32.Polyline` doesn't update FChange 

I can see now that this is necessary when further points need to be added to the path (before ending that path). I just need to append EndPath explicitly. 

Also, I'd suggest changing the `Points` property to `Buffer` or something else to indicate that this is primarily temporary storage for constructing a path.

**Comment by andersmelander** [comment] 2019-04-12 09:46
> I can see now that this is necessary when further points need to be added to the path (before ending that path). I just need to append EndPath explicitly.

Correct.

> Also, I'd suggest changing the Points property to Buffer or something else to indicate that this is primarily temporary storage for constructing a path.

I've just made it protected and added a comment to explain its use.

> `TCanvas32.PolyPolygon`

Added.
Calls `Polygon` on each individual polygon.
Whole thing wrapped in `BeginUpdate`...`EndUpdate`.

I'm a bit concerned about the `Polygon` method.
`TCustomPath.Polygon` starts by doing a `MoveTo(APoints[0])`. This ends any current path and starts a new.
`TFlattenedPath.Polygon` just does a Polyline(APoints) and will thus continue any existing path.
I'm not sure which of the two is the correct, but it smells like a bug.

There's also the problem I've marked with a TODO in `TCustomPath.Polygon`: Previously it didn't close the path. This may be by design, but without knowing what the design is it more looks like an omission.

> `TCanvas32.PolyPolyline`

Added.
Calls `Polyline` on each individual polyline. Calls `EndPath` after first polyline.
Whole thing wrapped in `BeginUpdate`...`EndUpdate`.

> Importantly, there's still no way to differentiate open and closed paths.

I'm working on that.
I started with the solution you originally proposed (having two different lists) but discarded it when I realized that we can't just reorder the paths. Their Z-order might be important to the final result.

What I'm doing now is storing the Closed status in a separate array and separating the final paths into chunks of closed and open paths, maintaining their individual order. This happens in `TCanvas32.DrawPath` so it doesn't affect any of the existing code that manipulates the path before it's rendered.

I can't see how using a special `TEndStyle` on the brush would help any. From you example it looks like the brush would be applied to all paths, closed and open.

> `TStrokeBrush`

Agree. I had noticed that as well and thought it might be a bug somewhere.
Can you take care of it?

> Here's an updated Polygons sample that demonstrates this...

Doesn't compile: It's missing your implementation of esClosed. Doesn't matter; I understand the principle.

**Comment by AngusJohnson** [comment] 2019-04-12 11:05
> > Also, I'd suggest changing the Points property to Buffer or something else to indicate that this is primarily temporary storage for constructing a path.
> 
> I've just made it protected and added a comment to explain its use.

I'd still like to have access to it (without having to hack a protected property).

> I'm a bit concerned about the `Polygon` method.

Since `Polygon` refers unambiguously to a closed path, it makes sense to me that `EndPath` is called implicitly for anything remaining in the Points buffer.

>I can't see how using a special `TEndStyle` on the brush would help any. From you example it looks like the brush would be applied to all paths, closed and open.

If you'd been able to compile the demo, you'd have seen that this isn't the case.

```
    //draw polygons (fill and stroke)
    FStroke.FillColor := SetAlpha(clNavy32, LineAlpha.Position);
    FStroke.StrokeWidth := LineThickness.Position/10;
    FSolid.FillColor := SetAlpha(clGreen32, FillAlpha.Position);
    FStroke.EndStyle := esClosed;
    FCanvas.Polygons(FClosedPaths); //renders closed stroke and fill paths

    //draw polylines (stroke only)
    FSolid.Visible := false;
    FStroke.FillColor := SetAlpha(clBlack32, LineAlpha.Position);
    //reset the end style here to an open style ...
    if RgpJointMode.ItemIndex = 2 then
      FStroke.EndStyle := esRound else
      FStroke.EndStyle := esSquare;
    //render open lines with implicit EndPath after each line (and no fill) 
    FCanvas.PolyLines(FOpenPaths); 

    //draw another line (stroke only) 
    FStroke.FillColor := clRed32;
    FCanvas.PolyLine(FPoints);
    FCanvas.EndLine(false);
```
![polygon](https://user-images.githubusercontent.com/5280692/56032884-96d37a80-5d66-11e9-9eea-ed95b8313101.png)

> > `TStrokeBrush`
> Agree. I had noticed that as well and thought it might be a bug somewhere.
Can you take care of it?

Will do.

**Comment by andersmelander** [comment] 2019-04-12 14:02
>> Points
> I'd still like to have access to it (without having to hack a protected property).

Why? I mean I can understand why it shouldn't be private but what's the use case for regular use where one would want access to it? I mean, it's an internal buffer...

> Since Polygon refers unambiguously to a closed path, it makes sense to me that EndPath is called implicitly for anything remaining in the Points buffer.

OK, so looking at the two different implementations of `Polygon` and the implementation of `Polyline` and `LineTo` I can see no reason why the `TCustomPath.Polygon` implementation should not be completely replaced with the one from `TFlattenedPath` - they end up calling the same sequence of methods.
There just needs to be an additional call to `EndPath` at the start of the `Polygon` method.

> If you'd been able to compile the demo, you'd have seen that this isn't the case.

That will only work if you're using TCanvas32 to render the paths. What of all the other use cases?

**Comment by andersmelander** [comment] 2019-04-12 14:40
I have pushed the latest changes to the [TCanvas32-redesign](TCanvas32-redesign) branch to avoid disturbing the plebs while we muck about.

**Comment by AngusJohnson** [comment] 2019-04-12 22:15
> Why? I mean I can understand why it shouldn't be private but what's the use case for regular use where one would want access to it? I mean, it's an internal buffer...

Yes, but imagine coding a path designer where you wanted to display both completed paths and also the incomplete path in the buffer (perhaps as a dashed line). If `Points `isn't exposed, the coder would have to store this incomplete path externally from `TPath `or hack the protected Points property. My suggestion is Keep `Points` public, but rename it `Buffer `so as to indicate that this isn't the normal way to access these points.

As a side note, I'd also suggest renaming `TCanvas32.DrawPath` to `TCanvas32.Draw` and drop the parameter (which is always Self). That should make clearer what is really happening there.

> That will only work if you're using TCanvas32 to render the paths. What of all the other use cases?

I agree that this is an incomplete solution and providing another way to differentiate open from closed paths is necessary too. However, I think it makes sense to add esClosed to the TEndStyle enumeration (just as many enumerations include xNone values), as this would give developers another way to indicated closed state.

ps: I've just tried to send you emails privately but my emails are being rejected as spam. Perhaps your mail server is wiser than I am :). Anyhow, I've asked my own ISP to get my IP address unblocked.

**Comment by andersmelander** [comment] 2019-04-12 22:34
No need for "hacks":
```
type
  TPathHelper = class helper for TFlattenedPath
  public
    property Points;
  end;
```

`DrawPath` to avoid confusion with `TCanvas.Draw` and because it accurately describes what it does. The reason for the parameter is to enable use of the settings in `TCanvas32` to draw other paths. AFAIR it was based on your own suggestion...

> I think it makes sense to add esClosed to the TEndStyle enumeration

I'm not sure of what the consequences would be. I mean, we would have to support this everywhere `TEndStyle` can be specified and the outer layers would also have to be able to deal with a polyline actually being a polygon because of some context applied to it. Is that really worth the effort - and risk?

p.s. Try gmail: anders.bo.melander@...

**Closed** 2019-04-29 12:40 UTC
